from __future__ import annotations

DOCUMENT_INGESTION_REQUESTED_V1 = "document.ingestion.requested.v1"
DOCUMENT_INGESTION_STATUS_UPDATED_V1 = "document.ingestion.status.updated.v1"
DOCUMENT_LIFECYCLE_ARCHIVED_V1 = "document.lifecycle.archived.v1"
DOCUMENT_LIFECYCLE_REMOVED_V1 = "document.lifecycle.removed.v1"

ENVELOPE_SCHEMA_VERSION = "1.0.0"

INGESTION_REQUESTED_PAYLOAD_SCHEMA_VERSION = "1.0.0"

ACCEPTED_EVENT_TYPES = frozenset(
    [
        DOCUMENT_INGESTION_REQUESTED_V1,
        DOCUMENT_INGESTION_STATUS_UPDATED_V1,
        DOCUMENT_LIFECYCLE_ARCHIVED_V1,
        DOCUMENT_LIFECYCLE_REMOVED_V1,
    ]
)

ACCEPTED_ENVELOPE_SCHEMA_VERSIONS = frozenset([ENVELOPE_SCHEMA_VERSION])
ACCEPTED_INGESTION_REQUESTED_SCHEMA_VERSIONS = frozenset(
    [INGESTION_REQUESTED_PAYLOAD_SCHEMA_VERSION]
)
