// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core/ai_tool/v1/tool_service.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParameterSchemaJson string                 `protobuf:"bytes,3,opt,name=parameter_schema_json,json=parameterSchemaJson,proto3" json:"parameter_schema_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_core_ai_tool_v1_tool_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameterSchemaJson() string {
	if x != nil {
		return x.ParameterSchemaJson
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_core_ai_tool_v1_tool_service_proto_rawDescGZIP(), []int{1}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_core_ai_tool_v1_tool_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ExecuteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_core_ai_tool_v1_tool_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ExecuteToolRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ExecuteToolRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ExecuteToolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExecuteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_ai_tool_v1_tool_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_core_ai_tool_v1_tool_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteToolResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ExecuteToolResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_core_ai_tool_v1_tool_service_proto protoreflect.FileDescriptor

const file_core_ai_tool_v1_tool_service_proto_rawDesc = "" +
	"\n" +
	"\"core/ai_tool/v1/tool_service.proto\x12\x0fcore.ai_tool.v1\x1a\x1bbuf/validate/validate.proto\"\x83\x01\n" +
	"\x0eToolDefinition\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\x15parameter_schema_json\x18\x03 \x01(\tR\x13parameterSchemaJson\"\x12\n" +
	"\x10ListToolsRequest\"J\n" +
	"\x11ListToolsResponse\x125\n" +
	"\x05tools\x18\x01 \x03(\v2\x1f.core.ai_tool.v1.ToolDefinitionR\x05tools\"\xa8\x01\n" +
	"\x12ExecuteToolRequest\x12\x1b\n" +
	"\x04tool\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04tool\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\x12)\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\taccountId\x12#\n" +
	"\auser_id\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\x06userId\"u\n" +
	"\x13ExecuteToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2\xbd\x01\n" +
	"\rAIToolService\x12R\n" +
	"\tListTools\x12!.core.ai_tool.v1.ListToolsRequest\x1a\".core.ai_tool.v1.ListToolsResponse\x12X\n" +
	"\vExecuteTool\x12#.core.ai_tool.v1.ExecuteToolRequest\x1a$.core.ai_tool.v1.ExecuteToolResponseB;Z9github.com/Final-Year-Project-G22/backend/core-backend/pbb\x06proto3"

var (
	file_core_ai_tool_v1_tool_service_proto_rawDescOnce sync.Once
	file_core_ai_tool_v1_tool_service_proto_rawDescData []byte
)

func file_core_ai_tool_v1_tool_service_proto_rawDescGZIP() []byte {
	file_core_ai_tool_v1_tool_service_proto_rawDescOnce.Do(func() {
		file_core_ai_tool_v1_tool_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_ai_tool_v1_tool_service_proto_rawDesc), len(file_core_ai_tool_v1_tool_service_proto_rawDesc)))
	})
	return file_core_ai_tool_v1_tool_service_proto_rawDescData
}

var file_core_ai_tool_v1_tool_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_core_ai_tool_v1_tool_service_proto_goTypes = []any{
	(*ToolDefinition)(nil),      // 0: core.ai_tool.v1.ToolDefinition
	(*ListToolsRequest)(nil),    // 1: core.ai_tool.v1.ListToolsRequest
	(*ListToolsResponse)(nil),   // 2: core.ai_tool.v1.ListToolsResponse
	(*ExecuteToolRequest)(nil),  // 3: core.ai_tool.v1.ExecuteToolRequest
	(*ExecuteToolResponse)(nil), // 4: core.ai_tool.v1.ExecuteToolResponse
}
var file_core_ai_tool_v1_tool_service_proto_depIdxs = []int32{
	0, // 0: core.ai_tool.v1.ListToolsResponse.tools:type_name -> core.ai_tool.v1.ToolDefinition
	1, // 1: core.ai_tool.v1.AIToolService.ListTools:input_type -> core.ai_tool.v1.ListToolsRequest
	3, // 2: core.ai_tool.v1.AIToolService.ExecuteTool:input_type -> core.ai_tool.v1.ExecuteToolRequest
	2, // 3: core.ai_tool.v1.AIToolService.ListTools:output_type -> core.ai_tool.v1.ListToolsResponse
	4, // 4: core.ai_tool.v1.AIToolService.ExecuteTool:output_type -> core.ai_tool.v1.ExecuteToolResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_ai_tool_v1_tool_service_proto_init() }
func file_core_ai_tool_v1_tool_service_proto_init() {
	if File_core_ai_tool_v1_tool_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_ai_tool_v1_tool_service_proto_rawDesc), len(file_core_ai_tool_v1_tool_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_ai_tool_v1_tool_service_proto_goTypes,
		DependencyIndexes: file_core_ai_tool_v1_tool_service_proto_depIdxs,
		MessageInfos:      file_core_ai_tool_v1_tool_service_proto_msgTypes,
	}.Build()
	File_core_ai_tool_v1_tool_service_proto = out.File
	file_core_ai_tool_v1_tool_service_proto_goTypes = nil
	file_core_ai_tool_v1_tool_service_proto_depIdxs = nil
}
