// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: core/ai_tool/v1/tool_service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ToolDefinition with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ToolDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolDefinition with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ToolDefinitionMultiError,
// or nil if none found.
func (m *ToolDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for ParameterSchemaJson

	if len(errors) > 0 {
		return ToolDefinitionMultiError(errors)
	}

	return nil
}

// ToolDefinitionMultiError is an error wrapping multiple validation errors
// returned by ToolDefinition.ValidateAll() if the designated constraints
// aren't met.
type ToolDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolDefinitionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolDefinitionMultiError) AllErrors() []error { return m }

// ToolDefinitionValidationError is the validation error returned by
// ToolDefinition.Validate if the designated constraints aren't met.
type ToolDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolDefinitionValidationError) ErrorName() string { return "ToolDefinitionValidationError" }

// Error satisfies the builtin error interface
func (e ToolDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolDefinitionValidationError{}

// Validate checks the field values on ListToolsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListToolsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListToolsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListToolsRequestMultiError, or nil if none found.
func (m *ListToolsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListToolsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListToolsRequestMultiError(errors)
	}

	return nil
}

// ListToolsRequestMultiError is an error wrapping multiple validation errors
// returned by ListToolsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListToolsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListToolsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListToolsRequestMultiError) AllErrors() []error { return m }

// ListToolsRequestValidationError is the validation error returned by
// ListToolsRequest.Validate if the designated constraints aren't met.
type ListToolsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListToolsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListToolsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListToolsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListToolsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListToolsRequestValidationError) ErrorName() string { return "ListToolsRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListToolsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListToolsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListToolsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListToolsRequestValidationError{}

// Validate checks the field values on ListToolsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListToolsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListToolsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListToolsResponseMultiError, or nil if none found.
func (m *ListToolsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListToolsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTools() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListToolsResponseValidationError{
						field:  fmt.Sprintf("Tools[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListToolsResponseValidationError{
						field:  fmt.Sprintf("Tools[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListToolsResponseValidationError{
					field:  fmt.Sprintf("Tools[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListToolsResponseMultiError(errors)
	}

	return nil
}

// ListToolsResponseMultiError is an error wrapping multiple validation errors
// returned by ListToolsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListToolsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListToolsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListToolsResponseMultiError) AllErrors() []error { return m }

// ListToolsResponseValidationError is the validation error returned by
// ListToolsResponse.Validate if the designated constraints aren't met.
type ListToolsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListToolsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListToolsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListToolsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListToolsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListToolsResponseValidationError) ErrorName() string {
	return "ListToolsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListToolsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListToolsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListToolsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListToolsResponseValidationError{}

// Validate checks the field values on ExecuteToolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteToolRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteToolRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteToolRequestMultiError, or nil if none found.
func (m *ExecuteToolRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteToolRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Tool

	// no validation rules for ArgumentsJson

	// no validation rules for AccountId

	// no validation rules for UserId

	if len(errors) > 0 {
		return ExecuteToolRequestMultiError(errors)
	}

	return nil
}

// ExecuteToolRequestMultiError is an error wrapping multiple validation errors
// returned by ExecuteToolRequest.ValidateAll() if the designated constraints
// aren't met.
type ExecuteToolRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteToolRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteToolRequestMultiError) AllErrors() []error { return m }

// ExecuteToolRequestValidationError is the validation error returned by
// ExecuteToolRequest.Validate if the designated constraints aren't met.
type ExecuteToolRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteToolRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteToolRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteToolRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteToolRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteToolRequestValidationError) ErrorName() string {
	return "ExecuteToolRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteToolRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteToolRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteToolRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteToolRequestValidationError{}

// Validate checks the field values on ExecuteToolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExecuteToolResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExecuteToolResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExecuteToolResponseMultiError, or nil if none found.
func (m *ExecuteToolResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExecuteToolResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for ResultJson

	// no validation rules for ErrorMessage

	if len(errors) > 0 {
		return ExecuteToolResponseMultiError(errors)
	}

	return nil
}

// ExecuteToolResponseMultiError is an error wrapping multiple validation
// errors returned by ExecuteToolResponse.ValidateAll() if the designated
// constraints aren't met.
type ExecuteToolResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExecuteToolResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExecuteToolResponseMultiError) AllErrors() []error { return m }

// ExecuteToolResponseValidationError is the validation error returned by
// ExecuteToolResponse.Validate if the designated constraints aren't met.
type ExecuteToolResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExecuteToolResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExecuteToolResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExecuteToolResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExecuteToolResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExecuteToolResponseValidationError) ErrorName() string {
	return "ExecuteToolResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExecuteToolResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExecuteToolResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExecuteToolResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExecuteToolResponseValidationError{}
