app:
  environment: "local"
  debug: true

logger:
  level: "debug"
  encoding: "console"
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

cache:
  enabled: false

jwt:
  access_token_ttl: 1h
  refresh_token_ttl: 720h

oauth:
  mobile_redirect_base_url: "adisu://auth/oauth/callback"
