package error

import "errors"

var (
	ErrTemplateNotFound               = errors.New("notification: template not found")
	ErrTemplateTypeConflict           = errors.New("notification: template type already exists")
	ErrTemplateSystemManaged          = errors.New("notification: system-managed template cannot be modified")
	ErrTranslationNotFound            = errors.New("notification: translation not found")
	ErrTranslationAlreadyExists       = errors.New("notification: translation already exists for this language")
	ErrPreferenceNotFound             = errors.New("notification: preference override not found")
	ErrMuteNotFound                   = errors.New("notification: mute not found")
	ErrAlreadyMuted                   = errors.New("notification: account already muted")
	ErrDeviceNotFound                 = errors.New("notification: device not found")
	ErrDeviceTokenAlreadyExists       = errors.New("notification: device token already registered")
	ErrQueueItemNotFound              = errors.New("notification: queue item not found")
	ErrHistoryNotFound                = errors.New("notification: history entry not found")
	ErrInboxEntryNotFound             = errors.New("notification: inbox entry not found")
	ErrCampaignNotFound               = errors.New("notification: campaign not found")
	ErrCampaignNotDraft               = errors.New("notification: campaign must be in draft status")
	ErrCampaignNotScheduled           = errors.New("notification: campaign is not scheduled")
	ErrCampaignInvalidTransition      = errors.New("notification: invalid campaign status transition")
	ErrDeliveryLogNotFound            = errors.New("notification: delivery log not found")
	ErrInvalidNotificationType        = errors.New("notification: invalid notification type")
	ErrInvalidChannel                 = errors.New("notification: invalid channel")
	ErrMuteResolverNotFound           = errors.New("notification: no mute resolver registered for this item type")
	ErrCampaignTemplateNotFound       = errors.New("notification: campaign template not found")
	ErrCampaignTranslationNotFound    = errors.New("notification: campaign template translation not found")
	ErrScheduledAlertNotFound         = errors.New("notification: scheduled alert not found")
	ErrMaxScheduledAlertsReached      = errors.New("notification: maximum scheduled alerts reached for non-pro user")
	ErrComplianceEntryNotFound        = errors.New("notification: compliance entry not found")
	ErrScheduledAlertTemplateNotFound = errors.New("notification: scheduled alert template not found")
)
