// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/ingestion/v1/events.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IngestionEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IngestionEventEnvelope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestionEventEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestionEventEnvelopeMultiError, or nil if none found.
func (m *IngestionEventEnvelope) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestionEventEnvelope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for EventType

	// no validation rules for SchemaVersion

	// no validation rules for OccurredAt

	// no validation rules for Producer

	// no validation rules for KeyId

	// no validation rules for Signature

	// no validation rules for IdempotencyKey

	// no validation rules for AccountId

	// no validation rules for UserId

	// no validation rules for BatchId

	// no validation rules for ReplayCount

	if all {
		switch v := interface{}(m.GetPayload()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IngestionEventEnvelopeValidationError{
					field:  "Payload",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IngestionEventEnvelopeValidationError{
					field:  "Payload",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayload()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IngestionEventEnvelopeValidationError{
				field:  "Payload",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return IngestionEventEnvelopeMultiError(errors)
	}

	return nil
}

// IngestionEventEnvelopeMultiError is an error wrapping multiple validation
// errors returned by IngestionEventEnvelope.ValidateAll() if the designated
// constraints aren't met.
type IngestionEventEnvelopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestionEventEnvelopeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestionEventEnvelopeMultiError) AllErrors() []error { return m }

// IngestionEventEnvelopeValidationError is the validation error returned by
// IngestionEventEnvelope.Validate if the designated constraints aren't met.
type IngestionEventEnvelopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestionEventEnvelopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestionEventEnvelopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestionEventEnvelopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestionEventEnvelopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestionEventEnvelopeValidationError) ErrorName() string {
	return "IngestionEventEnvelopeValidationError"
}

// Error satisfies the builtin error interface
func (e IngestionEventEnvelopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestionEventEnvelope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestionEventEnvelopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestionEventEnvelopeValidationError{}

// Validate checks the field values on IngestionPayload with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IngestionPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestionPayload with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestionPayloadMultiError, or nil if none found.
func (m *IngestionPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestionPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Payload.(type) {
	case *IngestionPayload_IngestionRequested:
		if v == nil {
			err := IngestionPayloadValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetIngestionRequested()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "IngestionRequested",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "IngestionRequested",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetIngestionRequested()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IngestionPayloadValidationError{
					field:  "IngestionRequested",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *IngestionPayload_IngestionStatusUpdated:
		if v == nil {
			err := IngestionPayloadValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetIngestionStatusUpdated()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "IngestionStatusUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "IngestionStatusUpdated",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetIngestionStatusUpdated()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IngestionPayloadValidationError{
					field:  "IngestionStatusUpdated",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *IngestionPayload_LifecycleArchived:
		if v == nil {
			err := IngestionPayloadValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetLifecycleArchived()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "LifecycleArchived",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "LifecycleArchived",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLifecycleArchived()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IngestionPayloadValidationError{
					field:  "LifecycleArchived",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *IngestionPayload_LifecycleRemoved:
		if v == nil {
			err := IngestionPayloadValidationError{
				field:  "Payload",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetLifecycleRemoved()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "LifecycleRemoved",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IngestionPayloadValidationError{
						field:  "LifecycleRemoved",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetLifecycleRemoved()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IngestionPayloadValidationError{
					field:  "LifecycleRemoved",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return IngestionPayloadMultiError(errors)
	}

	return nil
}

// IngestionPayloadMultiError is an error wrapping multiple validation errors
// returned by IngestionPayload.ValidateAll() if the designated constraints
// aren't met.
type IngestionPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestionPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestionPayloadMultiError) AllErrors() []error { return m }

// IngestionPayloadValidationError is the validation error returned by
// IngestionPayload.Validate if the designated constraints aren't met.
type IngestionPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestionPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestionPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestionPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestionPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestionPayloadValidationError) ErrorName() string { return "IngestionPayloadValidationError" }

// Error satisfies the builtin error interface
func (e IngestionPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestionPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestionPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestionPayloadValidationError{}

// Validate checks the field values on DocumentIngestionRequestedPayload with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DocumentIngestionRequestedPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentIngestionRequestedPayload
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DocumentIngestionRequestedPayloadMultiError, or nil if none found.
func (m *DocumentIngestionRequestedPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentIngestionRequestedPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for StorageKey

	// no validation rules for ContentType

	// no validation rules for SizeBytes

	// no validation rules for ChecksumSha256

	// no validation rules for SourceFilename

	// no validation rules for DeclaredLanguage

	// no validation rules for PayloadSchemaVersion

	if len(errors) > 0 {
		return DocumentIngestionRequestedPayloadMultiError(errors)
	}

	return nil
}

// DocumentIngestionRequestedPayloadMultiError is an error wrapping multiple
// validation errors returned by
// DocumentIngestionRequestedPayload.ValidateAll() if the designated
// constraints aren't met.
type DocumentIngestionRequestedPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentIngestionRequestedPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentIngestionRequestedPayloadMultiError) AllErrors() []error { return m }

// DocumentIngestionRequestedPayloadValidationError is the validation error
// returned by DocumentIngestionRequestedPayload.Validate if the designated
// constraints aren't met.
type DocumentIngestionRequestedPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentIngestionRequestedPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentIngestionRequestedPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentIngestionRequestedPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentIngestionRequestedPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentIngestionRequestedPayloadValidationError) ErrorName() string {
	return "DocumentIngestionRequestedPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e DocumentIngestionRequestedPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentIngestionRequestedPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentIngestionRequestedPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentIngestionRequestedPayloadValidationError{}

// Validate checks the field values on DocumentIngestionStatusUpdatedPayload
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *DocumentIngestionStatusUpdatedPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentIngestionStatusUpdatedPayload
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// DocumentIngestionStatusUpdatedPayloadMultiError, or nil if none found.
func (m *DocumentIngestionStatusUpdatedPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentIngestionStatusUpdatedPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for IngestionId

	// no validation rules for Stage

	// no validation rules for Message

	// no validation rules for PayloadSchemaVersion

	if len(errors) > 0 {
		return DocumentIngestionStatusUpdatedPayloadMultiError(errors)
	}

	return nil
}

// DocumentIngestionStatusUpdatedPayloadMultiError is an error wrapping
// multiple validation errors returned by
// DocumentIngestionStatusUpdatedPayload.ValidateAll() if the designated
// constraints aren't met.
type DocumentIngestionStatusUpdatedPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentIngestionStatusUpdatedPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentIngestionStatusUpdatedPayloadMultiError) AllErrors() []error { return m }

// DocumentIngestionStatusUpdatedPayloadValidationError is the validation error
// returned by DocumentIngestionStatusUpdatedPayload.Validate if the
// designated constraints aren't met.
type DocumentIngestionStatusUpdatedPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentIngestionStatusUpdatedPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentIngestionStatusUpdatedPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentIngestionStatusUpdatedPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentIngestionStatusUpdatedPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentIngestionStatusUpdatedPayloadValidationError) ErrorName() string {
	return "DocumentIngestionStatusUpdatedPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e DocumentIngestionStatusUpdatedPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentIngestionStatusUpdatedPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentIngestionStatusUpdatedPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentIngestionStatusUpdatedPayloadValidationError{}

// Validate checks the field values on DocumentLifecycleArchivedPayload with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *DocumentLifecycleArchivedPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentLifecycleArchivedPayload with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DocumentLifecycleArchivedPayloadMultiError, or nil if none found.
func (m *DocumentLifecycleArchivedPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentLifecycleArchivedPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for PayloadSchemaVersion

	if len(errors) > 0 {
		return DocumentLifecycleArchivedPayloadMultiError(errors)
	}

	return nil
}

// DocumentLifecycleArchivedPayloadMultiError is an error wrapping multiple
// validation errors returned by
// DocumentLifecycleArchivedPayload.ValidateAll() if the designated
// constraints aren't met.
type DocumentLifecycleArchivedPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentLifecycleArchivedPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentLifecycleArchivedPayloadMultiError) AllErrors() []error { return m }

// DocumentLifecycleArchivedPayloadValidationError is the validation error
// returned by DocumentLifecycleArchivedPayload.Validate if the designated
// constraints aren't met.
type DocumentLifecycleArchivedPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentLifecycleArchivedPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentLifecycleArchivedPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentLifecycleArchivedPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentLifecycleArchivedPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentLifecycleArchivedPayloadValidationError) ErrorName() string {
	return "DocumentLifecycleArchivedPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e DocumentLifecycleArchivedPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentLifecycleArchivedPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentLifecycleArchivedPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentLifecycleArchivedPayloadValidationError{}

// Validate checks the field values on DocumentLifecycleRemovedPayload with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DocumentLifecycleRemovedPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DocumentLifecycleRemovedPayload with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DocumentLifecycleRemovedPayloadMultiError, or nil if none found.
func (m *DocumentLifecycleRemovedPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *DocumentLifecycleRemovedPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for PayloadSchemaVersion

	if len(errors) > 0 {
		return DocumentLifecycleRemovedPayloadMultiError(errors)
	}

	return nil
}

// DocumentLifecycleRemovedPayloadMultiError is an error wrapping multiple
// validation errors returned by DocumentLifecycleRemovedPayload.ValidateAll()
// if the designated constraints aren't met.
type DocumentLifecycleRemovedPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentLifecycleRemovedPayloadMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentLifecycleRemovedPayloadMultiError) AllErrors() []error { return m }

// DocumentLifecycleRemovedPayloadValidationError is the validation error
// returned by DocumentLifecycleRemovedPayload.Validate if the designated
// constraints aren't met.
type DocumentLifecycleRemovedPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentLifecycleRemovedPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentLifecycleRemovedPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentLifecycleRemovedPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentLifecycleRemovedPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentLifecycleRemovedPayloadValidationError) ErrorName() string {
	return "DocumentLifecycleRemovedPayloadValidationError"
}

// Error satisfies the builtin error interface
func (e DocumentLifecycleRemovedPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocumentLifecycleRemovedPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentLifecycleRemovedPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentLifecycleRemovedPayloadValidationError{}
