// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/ingestion/v1/events.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestionEventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique event identifier (UUID v4).
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Dot-notation event type with version suffix.
	// Example: "document.ingestion.requested.v1"
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Semantic schema version following the envelope contract.
	// Example: "1.0.0"
	SchemaVersion string `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// ISO 8601 / RFC 3339 timestamp of when the event occurred.
	OccurredAt string `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Identity of the service that produced the event.
	// Example: "core-backend"
	Producer string `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	// HMAC key identifier used to produce the signature.
	// Enables key rotation: consumers look up the key by id.
	KeyId string `protobuf:"bytes,6,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// HMAC-SHA256 signature over the canonical serialisation of the envelope
	// (see doc.md for canonical ordering).  The signature covers all fields
	// except itself.  When verifying, the consumer MUST exclude this field
	// from the signed payload and recompute.
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Deduplication key.  Producers MUST set this to a stable value per
	// business operation (e.g. finalise-upload request idempotency key).
	// Consumers MUST treat duplicate deliveries of the same idempotency_key
	// as no-ops.
	IdempotencyKey string `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Account (tenant) that owns the document.
	AccountId string `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// User who initiated the operation.
	UserId string `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Optional grouping key for batch uploads.  When set, all events that
	// share the same batch_id belong to the same logical upload batch.
	BatchId string `protobuf:"bytes,11,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// Number of times this event has been re-delivered from the outbox.
	// First delivery = 0.  Increments on each outbox retry.
	ReplayCount int32 `protobuf:"varint,12,opt,name=replay_count,json=replayCount,proto3" json:"replay_count,omitempty"`
	// Typed payload.  Exactly one variant MUST be set.
	Payload       *IngestionPayload `protobuf:"bytes,13,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionEventEnvelope) Reset() {
	*x = IngestionEventEnvelope{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionEventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionEventEnvelope) ProtoMessage() {}

func (x *IngestionEventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionEventEnvelope.ProtoReflect.Descriptor instead.
func (*IngestionEventEnvelope) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *IngestionEventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestionEventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IngestionEventEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *IngestionEventEnvelope) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *IngestionEventEnvelope) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *IngestionEventEnvelope) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *IngestionEventEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *IngestionEventEnvelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *IngestionEventEnvelope) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *IngestionEventEnvelope) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IngestionEventEnvelope) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *IngestionEventEnvelope) GetReplayCount() int32 {
	if x != nil {
		return x.ReplayCount
	}
	return 0
}

func (x *IngestionEventEnvelope) GetPayload() *IngestionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IngestionPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IngestionPayload_IngestionRequested
	//	*IngestionPayload_IngestionStatusUpdated
	//	*IngestionPayload_LifecycleArchived
	//	*IngestionPayload_LifecycleRemoved
	Payload       isIngestionPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionPayload) Reset() {
	*x = IngestionPayload{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionPayload) ProtoMessage() {}

func (x *IngestionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionPayload.ProtoReflect.Descriptor instead.
func (*IngestionPayload) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *IngestionPayload) GetPayload() isIngestionPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestionPayload) GetIngestionRequested() *DocumentIngestionRequestedPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestionPayload_IngestionRequested); ok {
			return x.IngestionRequested
		}
	}
	return nil
}

func (x *IngestionPayload) GetIngestionStatusUpdated() *DocumentIngestionStatusUpdatedPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestionPayload_IngestionStatusUpdated); ok {
			return x.IngestionStatusUpdated
		}
	}
	return nil
}

func (x *IngestionPayload) GetLifecycleArchived() *DocumentLifecycleArchivedPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestionPayload_LifecycleArchived); ok {
			return x.LifecycleArchived
		}
	}
	return nil
}

func (x *IngestionPayload) GetLifecycleRemoved() *DocumentLifecycleRemovedPayload {
	if x != nil {
		if x, ok := x.Payload.(*IngestionPayload_LifecycleRemoved); ok {
			return x.LifecycleRemoved
		}
	}
	return nil
}

type isIngestionPayload_Payload interface {
	isIngestionPayload_Payload()
}

type IngestionPayload_IngestionRequested struct {
	IngestionRequested *DocumentIngestionRequestedPayload `protobuf:"bytes,1,opt,name=ingestion_requested,json=ingestionRequested,proto3,oneof"`
}

type IngestionPayload_IngestionStatusUpdated struct {
	IngestionStatusUpdated *DocumentIngestionStatusUpdatedPayload `protobuf:"bytes,2,opt,name=ingestion_status_updated,json=ingestionStatusUpdated,proto3,oneof"`
}

type IngestionPayload_LifecycleArchived struct {
	LifecycleArchived *DocumentLifecycleArchivedPayload `protobuf:"bytes,3,opt,name=lifecycle_archived,json=lifecycleArchived,proto3,oneof"`
}

type IngestionPayload_LifecycleRemoved struct {
	LifecycleRemoved *DocumentLifecycleRemovedPayload `protobuf:"bytes,4,opt,name=lifecycle_removed,json=lifecycleRemoved,proto3,oneof"`
}

func (*IngestionPayload_IngestionRequested) isIngestionPayload_Payload() {}

func (*IngestionPayload_IngestionStatusUpdated) isIngestionPayload_Payload() {}

func (*IngestionPayload_LifecycleArchived) isIngestionPayload_Payload() {}

func (*IngestionPayload_LifecycleRemoved) isIngestionPayload_Payload() {}

type DocumentIngestionRequestedPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the ingestion job/document record.
	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// Storage object key (path) pointing to the uploaded file.
	// AI workers fetch content via short-lived signed URLs.
	StorageKey string `protobuf:"bytes,2,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	// MIME content type as declared by the client during finalisation.
	// Example: "application/pdf"
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Object size in bytes as declared by the client and verified by core.
	SizeBytes int64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// SHA-256 hex digest of the uploaded object, verified by core.
	ChecksumSha256 string `protobuf:"bytes,5,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	// Original filename as provided by the client (optional).
	SourceFilename string `protobuf:"bytes,6,opt,name=source_filename,json=sourceFilename,proto3" json:"source_filename,omitempty"`
	// Language hint declared by the client (optional).
	// ISO 639-1 code, e.g. "en", "am".
	DeclaredLanguage string `protobuf:"bytes,7,opt,name=declared_language,json=declaredLanguage,proto3" json:"declared_language,omitempty"`
	// Schema version of the ingestion-requested payload itself.
	// Allows the payload contract to evolve independently of the envelope.
	PayloadSchemaVersion string `protobuf:"bytes,8,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DocumentIngestionRequestedPayload) Reset() {
	*x = DocumentIngestionRequestedPayload{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIngestionRequestedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIngestionRequestedPayload) ProtoMessage() {}

func (x *DocumentIngestionRequestedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIngestionRequestedPayload.ProtoReflect.Descriptor instead.
func (*DocumentIngestionRequestedPayload) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentIngestionRequestedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DocumentIngestionRequestedPayload) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetSourceFilename() string {
	if x != nil {
		return x.SourceFilename
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetDeclaredLanguage() string {
	if x != nil {
		return x.DeclaredLanguage
	}
	return ""
}

func (x *DocumentIngestionRequestedPayload) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

type DocumentIngestionStatusUpdatedPayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DocumentId  string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	IngestionId string                 `protobuf:"bytes,2,opt,name=ingestion_id,json=ingestionId,proto3" json:"ingestion_id,omitempty"`
	// Ingestion stage, matching the AI worker state machine.
	// One of: queued, validating, fetching, chunking, embedding, indexing,
	// completed, failed, cancelled.
	Stage string `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	// Human-readable detail or error message (optional).
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Schema version of this payload type.
	PayloadSchemaVersion string `protobuf:"bytes,5,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DocumentIngestionStatusUpdatedPayload) Reset() {
	*x = DocumentIngestionStatusUpdatedPayload{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIngestionStatusUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIngestionStatusUpdatedPayload) ProtoMessage() {}

func (x *DocumentIngestionStatusUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIngestionStatusUpdatedPayload.ProtoReflect.Descriptor instead.
func (*DocumentIngestionStatusUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentIngestionStatusUpdatedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentIngestionStatusUpdatedPayload) GetIngestionId() string {
	if x != nil {
		return x.IngestionId
	}
	return ""
}

func (x *DocumentIngestionStatusUpdatedPayload) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DocumentIngestionStatusUpdatedPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DocumentIngestionStatusUpdatedPayload) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

type DocumentLifecycleArchivedPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DocumentId           string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PayloadSchemaVersion string                 `protobuf:"bytes,2,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DocumentLifecycleArchivedPayload) Reset() {
	*x = DocumentLifecycleArchivedPayload{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentLifecycleArchivedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentLifecycleArchivedPayload) ProtoMessage() {}

func (x *DocumentLifecycleArchivedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentLifecycleArchivedPayload.ProtoReflect.Descriptor instead.
func (*DocumentLifecycleArchivedPayload) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentLifecycleArchivedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentLifecycleArchivedPayload) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

type DocumentLifecycleRemovedPayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DocumentId           string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PayloadSchemaVersion string                 `protobuf:"bytes,2,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DocumentLifecycleRemovedPayload) Reset() {
	*x = DocumentLifecycleRemovedPayload{}
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentLifecycleRemovedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentLifecycleRemovedPayload) ProtoMessage() {}

func (x *DocumentLifecycleRemovedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ingestion_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentLifecycleRemovedPayload.ProtoReflect.Descriptor instead.
func (*DocumentLifecycleRemovedPayload) Descriptor() ([]byte, []int) {
	return file_ai_ingestion_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentLifecycleRemovedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentLifecycleRemovedPayload) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

var File_ai_ingestion_v1_events_proto protoreflect.FileDescriptor

const file_ai_ingestion_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1cai/ingestion/v1/events.proto\x12\x0fai.ingestion.v1\x1a\x1bbuf/validate/validate.proto\"\xa3\x04\n" +
	"\x16IngestionEventEnvelope\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12&\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\teventType\x12.\n" +
	"\x0eschema_version\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rschemaVersion\x12(\n" +
	"\voccurred_at\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"occurredAt\x12#\n" +
	"\bproducer\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bproducer\x12\x1e\n" +
	"\x06key_id\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05keyId\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x120\n" +
	"\x0fidempotency_key\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0eidempotencyKey\x12'\n" +
	"\n" +
	"account_id\x18\t \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12!\n" +
	"\auser_id\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x19\n" +
	"\bbatch_id\x18\v \x01(\tR\abatchId\x12!\n" +
	"\freplay_count\x18\f \x01(\x05R\vreplayCount\x12C\n" +
	"\apayload\x18\r \x01(\v2!.ai.ingestion.v1.IngestionPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\"\xbd\x03\n" +
	"\x10IngestionPayload\x12e\n" +
	"\x13ingestion_requested\x18\x01 \x01(\v22.ai.ingestion.v1.DocumentIngestionRequestedPayloadH\x00R\x12ingestionRequested\x12r\n" +
	"\x18ingestion_status_updated\x18\x02 \x01(\v26.ai.ingestion.v1.DocumentIngestionStatusUpdatedPayloadH\x00R\x16ingestionStatusUpdated\x12b\n" +
	"\x12lifecycle_archived\x18\x03 \x01(\v21.ai.ingestion.v1.DocumentLifecycleArchivedPayloadH\x00R\x11lifecycleArchived\x12_\n" +
	"\x11lifecycle_removed\x18\x04 \x01(\v20.ai.ingestion.v1.DocumentLifecycleRemovedPayloadH\x00R\x10lifecycleRemovedB\t\n" +
	"\apayload\"\x93\x03\n" +
	"!DocumentIngestionRequestedPayload\x12)\n" +
	"\vdocument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"documentId\x12(\n" +
	"\vstorage_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"storageKey\x12*\n" +
	"\fcontent_type\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vcontentType\x12&\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\tsizeBytes\x120\n" +
	"\x0fchecksum_sha256\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0echecksumSha256\x12'\n" +
	"\x0fsource_filename\x18\x06 \x01(\tR\x0esourceFilename\x12+\n" +
	"\x11declared_language\x18\a \x01(\tR\x10declaredLanguage\x12=\n" +
	"\x16payload_schema_version\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x14payloadSchemaVersion\"\xf7\x01\n" +
	"%DocumentIngestionStatusUpdatedPayload\x12)\n" +
	"\vdocument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"documentId\x12+\n" +
	"\fingestion_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\vingestionId\x12\x1d\n" +
	"\x05stage\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05stage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12=\n" +
	"\x16payload_schema_version\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x14payloadSchemaVersion\"\x8c\x01\n" +
	" DocumentLifecycleArchivedPayload\x12)\n" +
	"\vdocument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"documentId\x12=\n" +
	"\x16payload_schema_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x14payloadSchemaVersion\"\x8b\x01\n" +
	"\x1fDocumentLifecycleRemovedPayload\x12)\n" +
	"\vdocument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"documentId\x12=\n" +
	"\x16payload_schema_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x14payloadSchemaVersionB;Z9github.com/Final-Year-Project-G22/backend/core-backend/pbb\x06proto3"

var (
	file_ai_ingestion_v1_events_proto_rawDescOnce sync.Once
	file_ai_ingestion_v1_events_proto_rawDescData []byte
)

func file_ai_ingestion_v1_events_proto_rawDescGZIP() []byte {
	file_ai_ingestion_v1_events_proto_rawDescOnce.Do(func() {
		file_ai_ingestion_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ingestion_v1_events_proto_rawDesc), len(file_ai_ingestion_v1_events_proto_rawDesc)))
	})
	return file_ai_ingestion_v1_events_proto_rawDescData
}

var file_ai_ingestion_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ai_ingestion_v1_events_proto_goTypes = []any{
	(*IngestionEventEnvelope)(nil),                // 0: ai.ingestion.v1.IngestionEventEnvelope
	(*IngestionPayload)(nil),                      // 1: ai.ingestion.v1.IngestionPayload
	(*DocumentIngestionRequestedPayload)(nil),     // 2: ai.ingestion.v1.DocumentIngestionRequestedPayload
	(*DocumentIngestionStatusUpdatedPayload)(nil), // 3: ai.ingestion.v1.DocumentIngestionStatusUpdatedPayload
	(*DocumentLifecycleArchivedPayload)(nil),      // 4: ai.ingestion.v1.DocumentLifecycleArchivedPayload
	(*DocumentLifecycleRemovedPayload)(nil),       // 5: ai.ingestion.v1.DocumentLifecycleRemovedPayload
}
var file_ai_ingestion_v1_events_proto_depIdxs = []int32{
	1, // 0: ai.ingestion.v1.IngestionEventEnvelope.payload:type_name -> ai.ingestion.v1.IngestionPayload
	2, // 1: ai.ingestion.v1.IngestionPayload.ingestion_requested:type_name -> ai.ingestion.v1.DocumentIngestionRequestedPayload
	3, // 2: ai.ingestion.v1.IngestionPayload.ingestion_status_updated:type_name -> ai.ingestion.v1.DocumentIngestionStatusUpdatedPayload
	4, // 3: ai.ingestion.v1.IngestionPayload.lifecycle_archived:type_name -> ai.ingestion.v1.DocumentLifecycleArchivedPayload
	5, // 4: ai.ingestion.v1.IngestionPayload.lifecycle_removed:type_name -> ai.ingestion.v1.DocumentLifecycleRemovedPayload
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ai_ingestion_v1_events_proto_init() }
func file_ai_ingestion_v1_events_proto_init() {
	if File_ai_ingestion_v1_events_proto != nil {
		return
	}
	file_ai_ingestion_v1_events_proto_msgTypes[1].OneofWrappers = []any{
		(*IngestionPayload_IngestionRequested)(nil),
		(*IngestionPayload_IngestionStatusUpdated)(nil),
		(*IngestionPayload_LifecycleArchived)(nil),
		(*IngestionPayload_LifecycleRemoved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ingestion_v1_events_proto_rawDesc), len(file_ai_ingestion_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_ingestion_v1_events_proto_goTypes,
		DependencyIndexes: file_ai_ingestion_v1_events_proto_depIdxs,
		MessageInfos:      file_ai_ingestion_v1_events_proto_msgTypes,
	}.Build()
	File_ai_ingestion_v1_events_proto = out.File
	file_ai_ingestion_v1_events_proto_goTypes = nil
	file_ai_ingestion_v1_events_proto_depIdxs = nil
}
