CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE "users" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"first_name" varchar(100) NOT NULL,"last_name" varchar(100) NOT NULL,"image_url" varchar(512),"bio" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_users_deleted_at" ON "users" ("deleted_at");
CREATE TABLE "accounts" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"user_id" uuid NOT NULL,"email" varchar(255) NOT NULL,"email_normalized" varchar(255) NOT NULL,"password_hash" varchar(255),"phone_number" varchar(50),"email_verified" boolean NOT NULL DEFAULT false,"phone_verified" boolean NOT NULL DEFAULT false,"status" varchar(64) NOT NULL DEFAULT 'pending_verification',"failed_login_attempts" bigint NOT NULL DEFAULT 0,"locked_until" timestamptz,"last_login_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_accounts_email_normalized" ON "accounts" ("email_normalized");
CREATE INDEX IF NOT EXISTS "idx_accounts_user_id" ON "accounts" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_accounts_deleted_at" ON "accounts" ("deleted_at");
CREATE TABLE "roles" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"code" varchar(100) NOT NULL,"name" varchar(100) NOT NULL,"description" text,"type" varchar(32) NOT NULL DEFAULT 'system',"is_system" boolean NOT NULL DEFAULT true,"is_mutable" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_roles_code" ON "roles" ("code");
CREATE INDEX IF NOT EXISTS "idx_roles_deleted_at" ON "roles" ("deleted_at");
CREATE TABLE "permissions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"code" varchar(150) NOT NULL,"name" varchar(150) NOT NULL,"description" text,"module" varchar(100) NOT NULL,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_permissions_module" ON "permissions" ("module");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_permissions_code" ON "permissions" ("code");
CREATE INDEX IF NOT EXISTS "idx_permissions_deleted_at" ON "permissions" ("deleted_at");
CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL,"permission_id" uuid NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_role_permissions_role_permission" ON "role_permissions" ("role_id","permission_id");
CREATE TABLE "role_assignments" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"role_id" uuid NOT NULL,"assigned_by" uuid NOT NULL,"expires_at" timestamptz,"revoked_at" timestamptz,"revoke_reason" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_role_assignments_assigned_by" ON "role_assignments" ("assigned_by");
CREATE INDEX IF NOT EXISTS "idx_role_assignments_role_id" ON "role_assignments" ("role_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_role_assignments_account_role" ON "role_assignments" ("account_id","role_id");
CREATE INDEX IF NOT EXISTS "idx_role_assignments_deleted_at" ON "role_assignments" ("deleted_at");
CREATE TABLE "sessions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"refresh_token_hash" varchar(255) NOT NULL,"user_agent" text,"ip_address" varchar(64),"last_active_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"expires_at" timestamptz NOT NULL,"revoked_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_sessions_expires_at" ON "sessions" ("expires_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_refresh_token_hash" ON "sessions" ("refresh_token_hash");
CREATE INDEX IF NOT EXISTS "idx_sessions_account_id" ON "sessions" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_deleted_at" ON "sessions" ("deleted_at");
CREATE TABLE "oauth_identities" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"provider" varchar(100) NOT NULL,"provider_subject" varchar(255) NOT NULL,"provider_email" varchar(255),"access_token" text,"refresh_token" text,"token_expires_at" timestamptz,"last_used_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_oauth_provider_subject" ON "oauth_identities" ("provider","provider_subject");
CREATE INDEX IF NOT EXISTS "idx_oauth_identities_account_id" ON "oauth_identities" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_oauth_identities_deleted_at" ON "oauth_identities" ("deleted_at");
CREATE TABLE "ai_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"default_model" varchar(100),"response_style" varchar(100),"temperature" decimal,"allow_data_retention" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_preferences_account_id" ON "ai_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_ai_preferences_deleted_at" ON "ai_preferences" ("deleted_at");
CREATE TABLE "template_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"default_template" varchar(100),"editor_mode" varchar(50),PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_template_preferences_account_id" ON "template_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_template_preferences_deleted_at" ON "template_preferences" ("deleted_at");
CREATE TABLE "account_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"language" varchar(10) NOT NULL DEFAULT 'en',"timezone" varchar(64) NOT NULL DEFAULT 'UTC',PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_account_preferences_account_id" ON "account_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_account_preferences_deleted_at" ON "account_preferences" ("deleted_at");
CREATE TABLE "notification_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"enable_email_notification" boolean NOT NULL DEFAULT true,"enable_sms_notification" boolean NOT NULL DEFAULT false,"enable_push_notification" boolean NOT NULL DEFAULT false,"campaign_digest_enabled" boolean NOT NULL DEFAULT true,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_notification_preferences_account_id" ON "notification_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_notification_preferences_deleted_at" ON "notification_preferences" ("deleted_at");
CREATE TABLE "community_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"allow_mentions" boolean NOT NULL DEFAULT true,"allow_replies" boolean NOT NULL DEFAULT true,"digest_enabled" boolean NOT NULL DEFAULT true,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_community_preferences_account_id" ON "community_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_community_preferences_deleted_at" ON "community_preferences" ("deleted_at");
CREATE TABLE "business_profiles" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"company_name" varchar(255) NOT NULL,"company_email" varchar(255) NOT NULL,"company_phone_number" varchar(50) NOT NULL,"business_type" varchar(100),"business_sector" varchar(100),"registration_number" varchar(100),"registration_date" date,"tax_identification_number" varchar(100),"trade_license_number" varchar(100),"location" varchar(255),"description" text,"logo_url" varchar(512),"banner_url" varchar(512),"social_links" JSONB NOT NULL DEFAULT '{}',PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_business_profiles_account_id" ON "business_profiles" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_business_profiles_deleted_at" ON "business_profiles" ("deleted_at");
ALTER TABLE "accounts" ADD CONSTRAINT "fk_users_accounts" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_permissions_role_permissions" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_roles_role_permissions" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_role_assignments_assigned_by_account" FOREIGN KEY ("assigned_by") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_accounts_role_assignments" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_roles_role_assignments" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "fk_accounts_sessions" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "oauth_identities" ADD CONSTRAINT "fk_accounts_o_auth_identities" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_preferences" ADD CONSTRAINT "fk_accounts_a_ipreference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "template_preferences" ADD CONSTRAINT "fk_accounts_template_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "account_preferences" ADD CONSTRAINT "fk_accounts_account_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification_preferences" ADD CONSTRAINT "fk_accounts_notification_pref" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "community_preferences" ADD CONSTRAINT "fk_accounts_community_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "business_profiles" ADD CONSTRAINT "fk_accounts_business_profile" FOREIGN KEY ("account_id") REFERENCES "accounts"("id");
