CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE "users" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"first_name" varchar(100) NOT NULL,"last_name" varchar(100) NOT NULL,"image_url" varchar(512),"bio" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_users_deleted_at" ON "users" ("deleted_at");
CREATE TABLE "accounts" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"user_id" uuid NOT NULL,"email" varchar(255) NOT NULL,"email_normalized" varchar(255) NOT NULL,"username" varchar(64),"username_normalized" varchar(64),"password_hash" varchar(255),"phone_number" varchar(50),"email_verified" boolean NOT NULL DEFAULT false,"phone_verified" boolean NOT NULL DEFAULT false,"status" varchar(64) NOT NULL DEFAULT 'pending_verification',"failed_login_attempts" bigint NOT NULL DEFAULT 0,"locked_until" timestamptz,"last_login_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_accounts_username_normalized" ON "accounts" ("username_normalized");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_accounts_email_normalized" ON "accounts" ("email_normalized");
CREATE INDEX IF NOT EXISTS "idx_accounts_user_id" ON "accounts" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_accounts_deleted_at" ON "accounts" ("deleted_at");
CREATE TABLE "account_email_otps" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"code_hash" varchar(255) NOT NULL,"expires_at" timestamptz NOT NULL,"consumed_at" timestamptz,"attempt_count" bigint NOT NULL DEFAULT 0,"resend_count" bigint NOT NULL DEFAULT 0,"last_sent_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_account_email_otps_expires_at" ON "account_email_otps" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_account_email_otps_account_id" ON "account_email_otps" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_account_email_otps_deleted_at" ON "account_email_otps" ("deleted_at");
CREATE TABLE "roles" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"code" varchar(100) NOT NULL,"name" varchar(100) NOT NULL,"description" text,"type" varchar(32) NOT NULL DEFAULT 'system',"is_system" boolean NOT NULL DEFAULT false,"is_mutable" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_roles_code" ON "roles" ("code");
CREATE INDEX IF NOT EXISTS "idx_roles_deleted_at" ON "roles" ("deleted_at");
CREATE TABLE "permissions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"code" varchar(150) NOT NULL,"name" varchar(150) NOT NULL,"description" text,"module" varchar(100) NOT NULL,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_permissions_module" ON "permissions" ("module");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_permissions_code" ON "permissions" ("code");
CREATE INDEX IF NOT EXISTS "idx_permissions_deleted_at" ON "permissions" ("deleted_at");
CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL,"permission_id" uuid NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_role_permissions_role_permission" ON "role_permissions" ("role_id","permission_id");
CREATE TABLE "role_assignments" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"role_id" uuid NOT NULL,"assigned_by" uuid NOT NULL,"expires_at" timestamptz,"revoked_at" timestamptz,"revoke_reason" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_role_assignments_assigned_by" ON "role_assignments" ("assigned_by");
CREATE INDEX IF NOT EXISTS "idx_role_assignments_role_id" ON "role_assignments" ("role_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_role_assignments_account_role" ON "role_assignments" ("account_id","role_id");
CREATE INDEX IF NOT EXISTS "idx_role_assignments_deleted_at" ON "role_assignments" ("deleted_at");
CREATE TABLE "sessions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"refresh_token_hash" varchar(255) NOT NULL,"user_agent" text,"ip_address" varchar(64),"last_active_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"expires_at" timestamptz NOT NULL,"revoked_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_sessions_expires_at" ON "sessions" ("expires_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_refresh_token_hash" ON "sessions" ("refresh_token_hash");
CREATE INDEX IF NOT EXISTS "idx_sessions_account_id" ON "sessions" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_deleted_at" ON "sessions" ("deleted_at");
CREATE TABLE "oauth_identities" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"provider" varchar(100) NOT NULL,"provider_subject" varchar(255) NOT NULL,"provider_email" varchar(255),"access_token" text,"refresh_token" text,"token_expires_at" timestamptz,"last_used_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_oauth_provider_subject" ON "oauth_identities" ("provider","provider_subject");
CREATE INDEX IF NOT EXISTS "idx_oauth_identities_account_id" ON "oauth_identities" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_oauth_identities_deleted_at" ON "oauth_identities" ("deleted_at");
CREATE TABLE "ai_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"default_model" varchar(100),"response_style" varchar(100),"temperature" decimal,"allow_data_retention" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_preferences_account_id" ON "ai_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_ai_preferences_deleted_at" ON "ai_preferences" ("deleted_at");
CREATE TABLE "template_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"default_template" varchar(100),"editor_mode" varchar(50),PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_template_preferences_account_id" ON "template_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_template_preferences_deleted_at" ON "template_preferences" ("deleted_at");
CREATE TABLE "account_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"language" varchar(10) NOT NULL DEFAULT 'en',"timezone" varchar(64) NOT NULL DEFAULT 'UTC',PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_account_preferences_account_id" ON "account_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_account_preferences_deleted_at" ON "account_preferences" ("deleted_at");
CREATE TABLE "notification_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"enable_email_notification" boolean NOT NULL DEFAULT true,"enable_sms_notification" boolean NOT NULL DEFAULT false,"enable_push_notification" boolean NOT NULL DEFAULT false,"campaign_digest_enabled" boolean NOT NULL DEFAULT true,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_notification_preferences_account_id" ON "notification_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_notification_preferences_deleted_at" ON "notification_preferences" ("deleted_at");
CREATE TABLE "community_preferences" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"allow_mentions" boolean NOT NULL DEFAULT true,"allow_replies" boolean NOT NULL DEFAULT true,"digest_enabled" boolean NOT NULL DEFAULT true,"mute_notifications" boolean NOT NULL DEFAULT false,"mute_duration" timestamptz,"block_notifications" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_community_preferences_account_id" ON "community_preferences" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_community_preferences_deleted_at" ON "community_preferences" ("deleted_at");
CREATE TABLE "business_profiles" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"company_name" varchar(255) NOT NULL,"company_email" varchar(255) NOT NULL,"company_phone_number" varchar(50) NOT NULL,"business_type" varchar(100),"business_sector" varchar(100),"registration_number" varchar(100),"registration_date" date,"tax_identification_number" varchar(100),"trade_license_number" varchar(100),"location" varchar(255),"description" text,"logo_url" varchar(512),"banner_url" varchar(512),"social_links" JSONB NOT NULL DEFAULT '{}',PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_business_profiles_account_id" ON "business_profiles" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_business_profiles_deleted_at" ON "business_profiles" ("deleted_at");
CREATE TABLE "guide_categories" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"slug" varchar(200) NOT NULL,"icon" varchar(100),"sort_order" bigint NOT NULL DEFAULT 0,"parent_category_id" uuid,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_guide_categories_parent" ON "guide_categories" ("parent_category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_guide_categories_slug_per_parent" ON "guide_categories" ("parent_category_id","slug");
CREATE INDEX IF NOT EXISTS "idx_guide_categories_deleted_at" ON "guide_categories" ("deleted_at");
CREATE TABLE "guides" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"category_id" uuid NOT NULL,"slug" varchar(200) NOT NULL,"icon" varchar(100),"sort_order" bigint NOT NULL DEFAULT 0,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_guides_category" ON "guides" ("category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_guides_slug_per_category" ON "guides" ("category_id","slug");
CREATE INDEX IF NOT EXISTS "idx_guides_deleted_at" ON "guides" ("deleted_at");
CREATE TABLE "guide_conditions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"guide_id" uuid NOT NULL,"condition_type" varchar(50) NOT NULL,"operator" varchar(20) NOT NULL,"condition_value" JSONB NOT NULL,"is_inverse" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_guide_conditions_guide" ON "guide_conditions" ("guide_id");
CREATE INDEX IF NOT EXISTS "idx_guide_conditions_deleted_at" ON "guide_conditions" ("deleted_at");
CREATE TABLE "guide_category_conditions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"category_id" uuid NOT NULL,"condition_type" varchar(50) NOT NULL,"operator" varchar(20) NOT NULL,"condition_value" JSONB NOT NULL,"is_inverse" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_guide_category_conditions_category" ON "guide_category_conditions" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_guide_category_conditions_deleted_at" ON "guide_category_conditions" ("deleted_at");
CREATE TABLE "guide_steps" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"guide_id" uuid NOT NULL,"slug" varchar(200) NOT NULL,"step_type" varchar(64) NOT NULL,"sort_order" bigint NOT NULL DEFAULT 0,"estimated_time" bigint,"difficulty_level" bigint,"is_optional" boolean NOT NULL DEFAULT false,"required_documents" JSONB NOT NULL DEFAULT '[]',"external_links" JSONB NOT NULL DEFAULT '[]',"fee_estimate" bigint,"version" bigint NOT NULL DEFAULT 1,"effective_date" date NOT NULL DEFAULT CURRENT_DATE,"expiry_date" date,PRIMARY KEY ("id"),CONSTRAINT "difficulty_level_check" CHECK (difficulty_level BETWEEN 1 AND 5));
CREATE INDEX IF NOT EXISTS "idx_guide_steps_guide" ON "guide_steps" ("guide_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_guide_steps_sort_per_guide" ON "guide_steps" ("guide_id","sort_order");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_guide_steps_slug_per_guide" ON "guide_steps" ("guide_id","slug");
CREATE INDEX IF NOT EXISTS "idx_guide_steps_deleted_at" ON "guide_steps" ("deleted_at");
CREATE TABLE "step_conditions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"step_id" uuid NOT NULL,"condition_type" varchar(50) NOT NULL,"operator" varchar(20) NOT NULL,"condition_value" JSONB NOT NULL,"is_inverse" boolean NOT NULL DEFAULT false,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_step_conditions_step" ON "step_conditions" ("step_id");
CREATE INDEX IF NOT EXISTS "idx_step_conditions_deleted_at" ON "step_conditions" ("deleted_at");
CREATE TABLE "step_dependencies" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"step_id" uuid NOT NULL,"required_step_id" uuid NOT NULL,"dependency_type" varchar(20) NOT NULL DEFAULT 'MANDATORY',PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_step_dependencies_required" ON "step_dependencies" ("required_step_id");
CREATE INDEX IF NOT EXISTS "idx_step_dependencies_step" ON "step_dependencies" ("step_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_step_dependencies_unique" ON "step_dependencies" ("step_id","required_step_id");
CREATE INDEX IF NOT EXISTS "idx_step_dependencies_deleted_at" ON "step_dependencies" ("deleted_at");
CREATE TABLE "user_guide_progresses" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"step_id" uuid NOT NULL,"status" varchar(20) NOT NULL DEFAULT 'LOCKED',"started_at" timestamptz,"completed_at" timestamptz,"time_spent" bigint,"notes" text,"uploaded_documents" JSONB NOT NULL DEFAULT '[]',"last_accessed_at" timestamptz,"version" bigint NOT NULL,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_progress_status" ON "user_guide_progresses" ("status");
CREATE INDEX IF NOT EXISTS "idx_user_progress_step" ON "user_guide_progresses" ("step_id");
CREATE INDEX IF NOT EXISTS "idx_user_progress_user" ON "user_guide_progresses" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_progress_account_user_step" ON "user_guide_progresses" ("account_id","user_id","step_id");
CREATE INDEX IF NOT EXISTS "idx_user_progress_account" ON "user_guide_progresses" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_user_guide_progresses_deleted_at" ON "user_guide_progresses" ("deleted_at");
CREATE TABLE "user_guide_journeys" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"guide_id" uuid NOT NULL,"journey_hash" text,"step_sequence" JSONB NOT NULL,"total_steps" bigint NOT NULL,"completed_steps" bigint NOT NULL DEFAULT 0,"estimated_total_time" bigint,"generated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"expires_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_journey_expires" ON "user_guide_journeys" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_journey_guide" ON "user_guide_journeys" ("guide_id");
CREATE INDEX IF NOT EXISTS "idx_journey_user" ON "user_guide_journeys" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_journey_account_user_guide" ON "user_guide_journeys" ("account_id","user_id","guide_id");
CREATE INDEX IF NOT EXISTS "idx_journey_account" ON "user_guide_journeys" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_user_guide_journeys_deleted_at" ON "user_guide_journeys" ("deleted_at");
CREATE TABLE "user_guide_bookmarks" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"step_id" uuid NOT NULL,"note" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_bookmarks_step" ON "user_guide_bookmarks" ("step_id");
CREATE INDEX IF NOT EXISTS "idx_bookmarks_user" ON "user_guide_bookmarks" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_bookmark_account_user_step" ON "user_guide_bookmarks" ("account_id","user_id","step_id");
CREATE INDEX IF NOT EXISTS "idx_bookmarks_account" ON "user_guide_bookmarks" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_user_guide_bookmarks_deleted_at" ON "user_guide_bookmarks" ("deleted_at");
CREATE TABLE "guide_step_versions" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"step_id" uuid NOT NULL,"version" bigint NOT NULL,"title" varchar(200) NOT NULL,"content" JSONB NOT NULL,"effective_date" date NOT NULL,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_versions_step" ON "guide_step_versions" ("step_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_version_step_version" ON "guide_step_versions" ("step_id","version");
CREATE INDEX IF NOT EXISTS "idx_guide_step_versions_deleted_at" ON "guide_step_versions" ("deleted_at");
CREATE TABLE "guide_category_translations" ("id" uuid DEFAULT gen_random_uuid(),"guide_category_id" uuid NOT NULL,"language" varchar(10) NOT NULL,"name" varchar(200) NOT NULL,"description" text,"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_cat_trans" ON "guide_category_translations" ("guide_category_id","language");
CREATE TABLE "guide_translations" ("id" uuid DEFAULT gen_random_uuid(),"guide_id" uuid NOT NULL,"language" varchar(10) NOT NULL,"name" varchar(200) NOT NULL,"description" text,"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_guide_trans" ON "guide_translations" ("guide_id","language");
CREATE TABLE "guide_step_translations" ("id" uuid DEFAULT gen_random_uuid(),"guide_step_id" uuid NOT NULL,"language" varchar(10) NOT NULL,"title" varchar(200) NOT NULL,"description" text,"detailed_content" JSONB NOT NULL DEFAULT '{}',"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_step_trans" ON "guide_step_translations" ("guide_step_id","language");
CREATE TABLE "user_guide_recent_views" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"guide_id" uuid NOT NULL,"last_viewed_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"view_count" bigint NOT NULL DEFAULT 1,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_recent_view_last_viewed" ON "user_guide_recent_views" ("last_viewed_at");
CREATE INDEX IF NOT EXISTS "idx_recent_view_guide" ON "user_guide_recent_views" ("guide_id");
CREATE INDEX IF NOT EXISTS "idx_recent_view_user" ON "user_guide_recent_views" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_recent_view_account" ON "user_guide_recent_views" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_recent_view_account_user_guide" ON "user_guide_recent_views" ("account_id","user_id","guide_id");
CREATE INDEX IF NOT EXISTS "idx_user_guide_recent_views_deleted_at" ON "user_guide_recent_views" ("deleted_at");
CREATE TABLE "community_categories" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"name" varchar(200) NOT NULL,"slug" varchar(200) NOT NULL,"description" text,"parent_category_id" uuid,"is_active" boolean NOT NULL DEFAULT true,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_community_categories_parent" ON "community_categories" ("parent_category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_community_categories_slug_per_parent" ON "community_categories" ("parent_category_id","slug");
CREATE INDEX IF NOT EXISTS "idx_community_categories_deleted_at" ON "community_categories" ("deleted_at");
CREATE TABLE "discussion_threads" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"category_id" uuid NOT NULL,"author_account_id" uuid NOT NULL,"title" varchar(200) NOT NULL,"slug" varchar(200) NOT NULL,"description" text,"is_pinned" boolean NOT NULL DEFAULT false,"status" varchar(20) NOT NULL DEFAULT 'active',"view_count" bigint NOT NULL DEFAULT 0,"share_count" bigint NOT NULL DEFAULT 0,"reply_count" bigint NOT NULL DEFAULT 0,"last_activity_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_discussion_threads_last_activity" ON "discussion_threads" ("last_activity_at");
CREATE INDEX IF NOT EXISTS "idx_discussion_threads_status" ON "discussion_threads" ("status");
CREATE INDEX IF NOT EXISTS "idx_discussion_threads_author" ON "discussion_threads" ("author_account_id");
CREATE INDEX IF NOT EXISTS "idx_discussion_threads_category" ON "discussion_threads" ("category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_discussion_threads_slug_per_category" ON "discussion_threads" ("category_id","slug");
CREATE INDEX IF NOT EXISTS "idx_discussion_threads_deleted_at" ON "discussion_threads" ("deleted_at");
CREATE TABLE "discussion_posts" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"thread_id" uuid NOT NULL,"parent_post_id" uuid,"author_account_id" uuid NOT NULL,"content" text NOT NULL,"is_solution" boolean NOT NULL DEFAULT false,"is_pinned" boolean NOT NULL DEFAULT false,"upvote_count" bigint NOT NULL DEFAULT 0,"attachment_url" text,"attachment_type" varchar(50),"edit_count" bigint NOT NULL DEFAULT 0,"edited_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_discussion_posts_solution" ON "discussion_posts" ("is_solution");
CREATE INDEX IF NOT EXISTS "idx_discussion_posts_author" ON "discussion_posts" ("author_account_id");
CREATE INDEX IF NOT EXISTS "idx_discussion_posts_parent" ON "discussion_posts" ("parent_post_id");
CREATE INDEX IF NOT EXISTS "idx_discussion_posts_thread" ON "discussion_posts" ("thread_id");
CREATE INDEX IF NOT EXISTS "idx_discussion_posts_deleted_at" ON "discussion_posts" ("deleted_at");
CREATE TABLE "user_thread_settings" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"thread_id" uuid NOT NULL,"is_following" boolean NOT NULL DEFAULT true,"is_muted" boolean NOT NULL DEFAULT false,"last_read_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_thread_settings_thread" ON "user_thread_settings" ("thread_id");
CREATE INDEX IF NOT EXISTS "idx_user_thread_settings_account" ON "user_thread_settings" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_thread_settings_account_thread" ON "user_thread_settings" ("account_id","thread_id");
CREATE INDEX IF NOT EXISTS "idx_user_thread_settings_deleted_at" ON "user_thread_settings" ("deleted_at");
CREATE TABLE "user_category_settings" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"category_id" uuid NOT NULL,"is_following" boolean NOT NULL DEFAULT true,"is_muted" boolean NOT NULL DEFAULT false,"last_read_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_category_settings_category" ON "user_category_settings" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_user_category_settings_account" ON "user_category_settings" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_user_category_settings_account_category" ON "user_category_settings" ("account_id","category_id");
CREATE INDEX IF NOT EXISTS "idx_user_category_settings_deleted_at" ON "user_category_settings" ("deleted_at");
CREATE TABLE "content_reports" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"reporter_account_id" uuid NOT NULL,"target_type" varchar(20) NOT NULL,"target_id" uuid NOT NULL,"reason" text NOT NULL,"status" varchar(20) NOT NULL DEFAULT 'pending',"admin_note" text,"resolved_by_account_id" uuid,"resolved_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_content_reports_resolved_by" ON "content_reports" ("resolved_by_account_id");
CREATE INDEX IF NOT EXISTS "idx_content_reports_status" ON "content_reports" ("status");
CREATE INDEX IF NOT EXISTS "idx_content_reports_target" ON "content_reports" ("target_type","target_id");
CREATE INDEX IF NOT EXISTS "idx_content_reports_reporter" ON "content_reports" ("reporter_account_id");
CREATE INDEX IF NOT EXISTS "idx_content_reports_deleted_at" ON "content_reports" ("deleted_at");
CREATE TABLE "thread_blocked_users" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"thread_id" uuid NOT NULL,"blocked_account_id" uuid NOT NULL,"blocked_by_account_id" uuid NOT NULL,"reason" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_thread_blocked_users_blocked_by" ON "thread_blocked_users" ("blocked_by_account_id");
CREATE INDEX IF NOT EXISTS "idx_thread_blocked_users_blocked" ON "thread_blocked_users" ("blocked_account_id");
CREATE INDEX IF NOT EXISTS "idx_thread_blocked_users_thread" ON "thread_blocked_users" ("thread_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_thread_blocked_users_thread_account" ON "thread_blocked_users" ("thread_id","blocked_account_id");
CREATE INDEX IF NOT EXISTS "idx_thread_blocked_users_deleted_at" ON "thread_blocked_users" ("deleted_at");
CREATE TABLE "ingestion_documents" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"storage_key" text NOT NULL,"content_type" varchar(255) NOT NULL,"size_bytes" bigint NOT NULL DEFAULT 0,"checksum_sha256" varchar(128) NOT NULL,"idempotency_key" varchar(255) NOT NULL,"batch_id" uuid,"source_filename" text,"declared_language" varchar(16),"schema_version" varchar(32) NOT NULL DEFAULT '1.0.0',"status" varchar(32) NOT NULL DEFAULT 'queued',"last_error" text,"event_id" uuid NOT NULL,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ingestion_documents_event_id" ON "ingestion_documents" ("event_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_status" ON "ingestion_documents" ("status");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_batch" ON "ingestion_documents" ("batch_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_storage_key" ON "ingestion_documents" ("storage_key");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_user" ON "ingestion_documents" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ingestion_docs_idempotency_per_account" ON "ingestion_documents" ("account_id","idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_account" ON "ingestion_documents" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_documents_deleted_at" ON "ingestion_documents" ("deleted_at");
CREATE TABLE "ingestion_outbox" ("id" uuid DEFAULT gen_random_uuid(),"created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" timestamptz,"event_id" uuid NOT NULL,"event_type" varchar(255) NOT NULL,"schema_version" varchar(32) NOT NULL DEFAULT '1.0.0',"producer" varchar(64) NOT NULL,"key_id" varchar(128) NOT NULL,"idempotency_key" varchar(255) NOT NULL,"aggregate_id" uuid NOT NULL,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"batch_id" uuid,"replay_count" integer NOT NULL DEFAULT 0,"payload" JSONB NOT NULL,"signature" bytea,"status" varchar(32) NOT NULL DEFAULT 'pending',"attempt_count" bigint NOT NULL DEFAULT 0,"next_attempt_at" timestamptz,"published_at" timestamptz,"last_error" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_status_next_attempt" ON "ingestion_outbox" ("status","next_attempt_at");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_batch" ON "ingestion_outbox" ("batch_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_user" ON "ingestion_outbox" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_account" ON "ingestion_outbox" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_aggregate" ON "ingestion_outbox" ("aggregate_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ingestion_outbox_dedupe" ON "ingestion_outbox" ("event_type","idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_event_type" ON "ingestion_outbox" ("event_type");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ingestion_outbox_event_id" ON "ingestion_outbox" ("event_id");
CREATE INDEX IF NOT EXISTS "idx_ingestion_outbox_deleted_at" ON "ingestion_outbox" ("deleted_at");
CREATE TABLE "ingestion_status_events" ("id" uuid,"event_id" varchar(100) NOT NULL,"document_id" uuid NOT NULL,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"event_type" varchar(100) NOT NULL,"schema_version" varchar(32) NOT NULL,"occurred_at" timestamp with time zone NOT NULL,"created_at" timestamp with time zone NOT NULL,"from_stage" varchar(32),"to_stage" varchar(32) NOT NULL,"is_terminal" boolean NOT NULL DEFAULT false,"retry_count" bigint NOT NULL DEFAULT 0,"error_message" text,"chunks_processed_count" bigint NOT NULL,"chunks_failed_count" bigint NOT NULL,"event_sequence" bigint NOT NULL DEFAULT 0,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ingestion_status_events_event_sequence" ON "ingestion_status_events" ("event_sequence");
CREATE INDEX IF NOT EXISTS "idx_status_user" ON "ingestion_status_events" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_status_account" ON "ingestion_status_events" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_status_document_occurred" ON "ingestion_status_events" ("document_id","occurred_at");
CREATE INDEX IF NOT EXISTS "idx_ingestion_status_events_event_id" ON "ingestion_status_events" ("event_id");
CREATE TABLE "ingestion_status_projections" ("id" uuid,"document_id" uuid NOT NULL,"account_id" uuid NOT NULL,"user_id" uuid NOT NULL,"event_id" varchar(100) NOT NULL,"current_stage" varchar(32) NOT NULL,"is_terminal" boolean NOT NULL DEFAULT false,"started_at" timestamp with time zone NOT NULL,"updated_at" timestamp with time zone NOT NULL,"completed_at" timestamp with time zone,"last_error" text,"chunks_processed_count" bigint NOT NULL DEFAULT 0,"chunks_failed_count" bigint NOT NULL DEFAULT 0,"last_event_sequence" bigint NOT NULL DEFAULT 0,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_projection_user" ON "ingestion_status_projections" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_projection_account" ON "ingestion_status_projections" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_projection_document" ON "ingestion_status_projections" ("document_id");
ALTER TABLE "accounts" ADD CONSTRAINT "fk_users_accounts" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "account_email_otps" ADD CONSTRAINT "fk_account_email_otps_account" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_permissions_role_permissions" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_roles_role_permissions" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_role_assignments_assigned_by_account" FOREIGN KEY ("assigned_by") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_accounts_role_assignments" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_assignments" ADD CONSTRAINT "fk_roles_role_assignments" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "fk_accounts_sessions" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "oauth_identities" ADD CONSTRAINT "fk_accounts_o_auth_identities" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_preferences" ADD CONSTRAINT "fk_accounts_a_ipreference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "template_preferences" ADD CONSTRAINT "fk_accounts_template_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "account_preferences" ADD CONSTRAINT "fk_accounts_account_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification_preferences" ADD CONSTRAINT "fk_accounts_notification_pref" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "community_preferences" ADD CONSTRAINT "fk_accounts_community_preference" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "business_profiles" ADD CONSTRAINT "fk_accounts_business_profile" FOREIGN KEY ("account_id") REFERENCES "accounts"("id");
ALTER TABLE "guide_categories" ADD CONSTRAINT "fk_guide_categories_child_categories" FOREIGN KEY ("parent_category_id") REFERENCES "guide_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "guides" ADD CONSTRAINT "fk_guide_categories_guides" FOREIGN KEY ("category_id") REFERENCES "guide_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_conditions" ADD CONSTRAINT "fk_guides_conditions" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_category_conditions" ADD CONSTRAINT "fk_guide_categories_conditions" FOREIGN KEY ("category_id") REFERENCES "guide_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_steps" ADD CONSTRAINT "fk_guides_steps" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "step_conditions" ADD CONSTRAINT "fk_guide_steps_conditions" FOREIGN KEY ("step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "step_dependencies" ADD CONSTRAINT "fk_guide_steps_dependencies" FOREIGN KEY ("step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "step_dependencies" ADD CONSTRAINT "fk_guide_steps_reverse_dependencies" FOREIGN KEY ("required_step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_guide_progresses" ADD CONSTRAINT "fk_guide_steps_progress" FOREIGN KEY ("step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_guide_journeys" ADD CONSTRAINT "fk_guides_journeys" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_guide_bookmarks" ADD CONSTRAINT "fk_guide_steps_bookmarks" FOREIGN KEY ("step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_step_versions" ADD CONSTRAINT "fk_guide_steps_versions" FOREIGN KEY ("step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_category_translations" ADD CONSTRAINT "fk_guide_categories_translations" FOREIGN KEY ("guide_category_id") REFERENCES "guide_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_translations" ADD CONSTRAINT "fk_guides_translations" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guide_step_translations" ADD CONSTRAINT "fk_guide_steps_translations" FOREIGN KEY ("guide_step_id") REFERENCES "guide_steps"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_guide_recent_views" ADD CONSTRAINT "fk_user_guide_recent_views_guide" FOREIGN KEY ("guide_id") REFERENCES "guides"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "community_categories" ADD CONSTRAINT "fk_community_categories_child_categories" FOREIGN KEY ("parent_category_id") REFERENCES "community_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "discussion_threads" ADD CONSTRAINT "fk_community_categories_threads" FOREIGN KEY ("category_id") REFERENCES "community_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "discussion_posts" ADD CONSTRAINT "fk_discussion_posts_replies" FOREIGN KEY ("parent_post_id") REFERENCES "discussion_posts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "discussion_posts" ADD CONSTRAINT "fk_discussion_threads_posts" FOREIGN KEY ("thread_id") REFERENCES "discussion_threads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_thread_settings" ADD CONSTRAINT "fk_discussion_threads_followers" FOREIGN KEY ("thread_id") REFERENCES "discussion_threads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_category_settings" ADD CONSTRAINT "fk_user_category_settings_category" FOREIGN KEY ("category_id") REFERENCES "community_categories"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "thread_blocked_users" ADD CONSTRAINT "fk_discussion_threads_blocks" FOREIGN KEY ("thread_id") REFERENCES "discussion_threads"("id") ON DELETE CASCADE ON UPDATE CASCADE;
