// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: core/document/v1/document.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSignedUrlRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSignedUrlRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSignedUrlRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSignedUrlRequestMultiError, or nil if none found.
func (m *GetSignedUrlRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSignedUrlRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for AccountId

	// no validation rules for ExpiresInSeconds

	if len(errors) > 0 {
		return GetSignedUrlRequestMultiError(errors)
	}

	return nil
}

// GetSignedUrlRequestMultiError is an error wrapping multiple validation
// errors returned by GetSignedUrlRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSignedUrlRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSignedUrlRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSignedUrlRequestMultiError) AllErrors() []error { return m }

// GetSignedUrlRequestValidationError is the validation error returned by
// GetSignedUrlRequest.Validate if the designated constraints aren't met.
type GetSignedUrlRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSignedUrlRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSignedUrlRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSignedUrlRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSignedUrlRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSignedUrlRequestValidationError) ErrorName() string {
	return "GetSignedUrlRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSignedUrlRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSignedUrlRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSignedUrlRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSignedUrlRequestValidationError{}

// Validate checks the field values on GetSignedUrlResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSignedUrlResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSignedUrlResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSignedUrlResponseMultiError, or nil if none found.
func (m *GetSignedUrlResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSignedUrlResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SignedUrl

	// no validation rules for ExpiresAt

	// no validation rules for ContentType

	// no validation rules for ContentLength

	if len(errors) > 0 {
		return GetSignedUrlResponseMultiError(errors)
	}

	return nil
}

// GetSignedUrlResponseMultiError is an error wrapping multiple validation
// errors returned by GetSignedUrlResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSignedUrlResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSignedUrlResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSignedUrlResponseMultiError) AllErrors() []error { return m }

// GetSignedUrlResponseValidationError is the validation error returned by
// GetSignedUrlResponse.Validate if the designated constraints aren't met.
type GetSignedUrlResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSignedUrlResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSignedUrlResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSignedUrlResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSignedUrlResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSignedUrlResponseValidationError) ErrorName() string {
	return "GetSignedUrlResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSignedUrlResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSignedUrlResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSignedUrlResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSignedUrlResponseValidationError{}
