// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: core/document/v1/document.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentFetchService_GetSignedUrl_FullMethodName = "/core.document.v1.DocumentFetchService/GetSignedUrl"
)

// DocumentFetchServiceClient is the client API for DocumentFetchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentFetchServiceClient interface {
	GetSignedUrl(ctx context.Context, in *GetSignedUrlRequest, opts ...grpc.CallOption) (*GetSignedUrlResponse, error)
}

type documentFetchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentFetchServiceClient(cc grpc.ClientConnInterface) DocumentFetchServiceClient {
	return &documentFetchServiceClient{cc}
}

func (c *documentFetchServiceClient) GetSignedUrl(ctx context.Context, in *GetSignedUrlRequest, opts ...grpc.CallOption) (*GetSignedUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSignedUrlResponse)
	err := c.cc.Invoke(ctx, DocumentFetchService_GetSignedUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentFetchServiceServer is the server API for DocumentFetchService service.
// All implementations must embed UnimplementedDocumentFetchServiceServer
// for forward compatibility.
type DocumentFetchServiceServer interface {
	GetSignedUrl(context.Context, *GetSignedUrlRequest) (*GetSignedUrlResponse, error)
	mustEmbedUnimplementedDocumentFetchServiceServer()
}

// UnimplementedDocumentFetchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentFetchServiceServer struct{}

func (UnimplementedDocumentFetchServiceServer) GetSignedUrl(context.Context, *GetSignedUrlRequest) (*GetSignedUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignedUrl not implemented")
}
func (UnimplementedDocumentFetchServiceServer) mustEmbedUnimplementedDocumentFetchServiceServer() {}
func (UnimplementedDocumentFetchServiceServer) testEmbeddedByValue()                              {}

// UnsafeDocumentFetchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentFetchServiceServer will
// result in compilation errors.
type UnsafeDocumentFetchServiceServer interface {
	mustEmbedUnimplementedDocumentFetchServiceServer()
}

func RegisterDocumentFetchServiceServer(s grpc.ServiceRegistrar, srv DocumentFetchServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentFetchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentFetchService_ServiceDesc, srv)
}

func _DocumentFetchService_GetSignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentFetchServiceServer).GetSignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentFetchService_GetSignedUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentFetchServiceServer).GetSignedUrl(ctx, req.(*GetSignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentFetchService_ServiceDesc is the grpc.ServiceDesc for DocumentFetchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentFetchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.document.v1.DocumentFetchService",
	HandlerType: (*DocumentFetchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSignedUrl",
			Handler:    _DocumentFetchService_GetSignedUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/document/v1/document.proto",
}
