// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core/document/v1/document.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSignedUrlRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentId       string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ExpiresInSeconds int32                  `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSignedUrlRequest) Reset() {
	*x = GetSignedUrlRequest{}
	mi := &file_core_document_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedUrlRequest) ProtoMessage() {}

func (x *GetSignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_document_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedUrlRequest.ProtoReflect.Descriptor instead.
func (*GetSignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_core_document_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *GetSignedUrlRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetSignedUrlRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetSignedUrlRequest) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type GetSignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedUrl     string                 `protobuf:"bytes,1,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ContentLength int64                  `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedUrlResponse) Reset() {
	*x = GetSignedUrlResponse{}
	mi := &file_core_document_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedUrlResponse) ProtoMessage() {}

func (x *GetSignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_document_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedUrlResponse.ProtoReflect.Descriptor instead.
func (*GetSignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_core_document_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *GetSignedUrlResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *GetSignedUrlResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetSignedUrlResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetSignedUrlResponse) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

var File_core_document_v1_document_proto protoreflect.FileDescriptor

const file_core_document_v1_document_proto_rawDesc = "" +
	"\n" +
	"\x1fcore/document/v1/document.proto\x12\x10core.document.v1\x1a\x1bbuf/validate/validate.proto\"\x9b\x01\n" +
	"\x13GetSignedUrlRequest\x12+\n" +
	"\vdocument_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\n" +
	"documentId\x12)\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\taccountId\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x05R\x10expiresInSeconds\"\x9e\x01\n" +
	"\x14GetSignedUrlResponse\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x01 \x01(\tR\tsignedUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12%\n" +
	"\x0econtent_length\x18\x04 \x01(\x03R\rcontentLength2u\n" +
	"\x14DocumentFetchService\x12]\n" +
	"\fGetSignedUrl\x12%.core.document.v1.GetSignedUrlRequest\x1a&.core.document.v1.GetSignedUrlResponseB;Z9github.com/Final-Year-Project-G22/backend/core-backend/pbb\x06proto3"

var (
	file_core_document_v1_document_proto_rawDescOnce sync.Once
	file_core_document_v1_document_proto_rawDescData []byte
)

func file_core_document_v1_document_proto_rawDescGZIP() []byte {
	file_core_document_v1_document_proto_rawDescOnce.Do(func() {
		file_core_document_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_document_v1_document_proto_rawDesc), len(file_core_document_v1_document_proto_rawDesc)))
	})
	return file_core_document_v1_document_proto_rawDescData
}

var file_core_document_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_document_v1_document_proto_goTypes = []any{
	(*GetSignedUrlRequest)(nil),  // 0: core.document.v1.GetSignedUrlRequest
	(*GetSignedUrlResponse)(nil), // 1: core.document.v1.GetSignedUrlResponse
}
var file_core_document_v1_document_proto_depIdxs = []int32{
	0, // 0: core.document.v1.DocumentFetchService.GetSignedUrl:input_type -> core.document.v1.GetSignedUrlRequest
	1, // 1: core.document.v1.DocumentFetchService.GetSignedUrl:output_type -> core.document.v1.GetSignedUrlResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_document_v1_document_proto_init() }
func file_core_document_v1_document_proto_init() {
	if File_core_document_v1_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_document_v1_document_proto_rawDesc), len(file_core_document_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_document_v1_document_proto_goTypes,
		DependencyIndexes: file_core_document_v1_document_proto_depIdxs,
		MessageInfos:      file_core_document_v1_document_proto_msgTypes,
	}.Build()
	File_core_document_v1_document_proto = out.File
	file_core_document_v1_document_proto_goTypes = nil
	file_core_document_v1_document_proto_depIdxs = nil
}
