package chapa

import (
	"encoding/json"
	"time"
)

// InitRequest is the payload for POST /v1/transaction/initialize.
type InitRequest struct {
	Amount        int64                  `json:"amount"`
	Currency      string                 `json:"currency"`
	Email         string                 `json:"email"`
	FirstName     string                 `json:"first_name"`
	LastName      string                 `json:"last_name"`
	Phone         string                 `json:"phone_number"`
	TxRef         string                 `json:"tx_ref"`
	CallbackURL   string                 `json:"callback_url"`
	ReturnURL     string                 `json:"return_url"`
	Customization map[string]interface{} `json:"customization,omitempty"`
}

// InitResponse is returned by Chapa after initializing a transaction.
type InitResponse struct {
	Message string           `json:"message"`
	Status  string           `json:"status"` // "success" or "error"
	Data    InitResponseData `json:"data"`
}

// InitResponseData holds the checkout URL generated by Chapa.
type InitResponseData struct {
	CheckoutURL string `json:"checkout_url"`
}

// VerifyResponse is returned by Chapa when verifying a transaction.
type VerifyResponse struct {
	Message string     `json:"message"`
	Status  string     `json:"status"`
	Data    VerifyData `json:"data"`
}

// VerifyData holds the transaction details from Chapa.
type VerifyData struct {
	TxRef         string      `json:"tx_ref"`
	Reference     string      `json:"reference"`
	Status        string      `json:"status"` // "success", "pending", "failed"
	Amount        json.Number `json:"amount"` // Chapa returns as string or number
	Charge        json.Number `json:"charge"`
	Currency      string      `json:"currency"`
	PaymentMethod string      `json:"payment_method"` // "telebirr", "cbebirr", etc.
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

// WebhookEvent represents a webhook payload sent by Chapa.
type WebhookEvent struct {
	Event         string                  `json:"event"`
	FirstName     string                  `json:"first_name"`
	LastName      string                  `json:"last_name"`
	Email         *string                 `json:"email"`
	Mobile        string                  `json:"mobile"`
	Currency      string                  `json:"currency"`
	Amount        json.Number             `json:"amount"`
	Charge        json.Number             `json:"charge"`
	Status        string                  `json:"status"`
	Mode          string                  `json:"mode"`
	Reference     string                  `json:"reference"`
	CreatedAt     time.Time               `json:"created_at"`
	UpdatedAt     time.Time               `json:"updated_at"`
	Type          string                  `json:"type"`
	TxRef         string                  `json:"tx_ref"`
	PaymentMethod string                  `json:"payment_method"`
	Customization map[string]interface{}  `json:"customization"`
	Meta          *map[string]interface{} `json:"meta"`
}

// Config holds the client configuration.
type Config struct {
	SecretKey string `json:"secret_key"` // e.g. CHASECK-test_...
	BaseURL   string `json:"base_url"`   // e.g. https://api.chapa.co/v1
}
