// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: core/user/v1/service.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreUserService_GetUserProfile_FullMethodName = "/core.user.v1.CoreUserService/GetUserProfile"
)

// CoreUserServiceClient is the client API for CoreUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreUserServiceClient interface {
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
}

type coreUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreUserServiceClient(cc grpc.ClientConnInterface) CoreUserServiceClient {
	return &coreUserServiceClient{cc}
}

func (c *coreUserServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, CoreUserService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreUserServiceServer is the server API for CoreUserService service.
// All implementations must embed UnimplementedCoreUserServiceServer
// for forward compatibility.
type CoreUserServiceServer interface {
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	mustEmbedUnimplementedCoreUserServiceServer()
}

// UnimplementedCoreUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreUserServiceServer struct{}

func (UnimplementedCoreUserServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedCoreUserServiceServer) mustEmbedUnimplementedCoreUserServiceServer() {}
func (UnimplementedCoreUserServiceServer) testEmbeddedByValue()                         {}

// UnsafeCoreUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreUserServiceServer will
// result in compilation errors.
type UnsafeCoreUserServiceServer interface {
	mustEmbedUnimplementedCoreUserServiceServer()
}

func RegisterCoreUserServiceServer(s grpc.ServiceRegistrar, srv CoreUserServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreUserService_ServiceDesc, srv)
}

func _CoreUserService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreUserServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreUserService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreUserServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreUserService_ServiceDesc is the grpc.ServiceDesc for CoreUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.user.v1.CoreUserService",
	HandlerType: (*CoreUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _CoreUserService_GetUserProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/user/v1/service.proto",
}
