// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: core/user/v1/service.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_core_user_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_user_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_core_user_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Tier              string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	PreferredLanguage string                 `protobuf:"bytes,4,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_core_user_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_user_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_core_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProfileResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetUserProfileResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *GetUserProfileResponse) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

var File_core_user_v1_service_proto protoreflect.FileDescriptor

const file_core_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1acore/user/v1/service.proto\x12\fcore.user.v1\x1a\x1bbuf/validate/validate.proto\"<\n" +
	"\x15GetUserProfileRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\x06userId\"\xd6\x01\n" +
	"\x16GetUserProfileResponse\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\x06userId\x12)\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\xb0\x01\x01R\taccountId\x12.\n" +
	"\x04tier\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15R\x05basicR\x03proR\apremiumR\x04tier\x12<\n" +
	"\x12preferred_language\x18\x04 \x01(\tB\r\xbaH\n" +
	"r\bR\x02enR\x02amR\x11preferredLanguage2n\n" +
	"\x0fCoreUserService\x12[\n" +
	"\x0eGetUserProfile\x12#.core.user.v1.GetUserProfileRequest\x1a$.core.user.v1.GetUserProfileResponseB;Z9github.com/Final-Year-Project-G22/backend/core-backend/pbb\x06proto3"

var (
	file_core_user_v1_service_proto_rawDescOnce sync.Once
	file_core_user_v1_service_proto_rawDescData []byte
)

func file_core_user_v1_service_proto_rawDescGZIP() []byte {
	file_core_user_v1_service_proto_rawDescOnce.Do(func() {
		file_core_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_user_v1_service_proto_rawDesc), len(file_core_user_v1_service_proto_rawDesc)))
	})
	return file_core_user_v1_service_proto_rawDescData
}

var file_core_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_user_v1_service_proto_goTypes = []any{
	(*GetUserProfileRequest)(nil),  // 0: core.user.v1.GetUserProfileRequest
	(*GetUserProfileResponse)(nil), // 1: core.user.v1.GetUserProfileResponse
}
var file_core_user_v1_service_proto_depIdxs = []int32{
	0, // 0: core.user.v1.CoreUserService.GetUserProfile:input_type -> core.user.v1.GetUserProfileRequest
	1, // 1: core.user.v1.CoreUserService.GetUserProfile:output_type -> core.user.v1.GetUserProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_user_v1_service_proto_init() }
func file_core_user_v1_service_proto_init() {
	if File_core_user_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_user_v1_service_proto_rawDesc), len(file_core_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_user_v1_service_proto_goTypes,
		DependencyIndexes: file_core_user_v1_service_proto_depIdxs,
		MessageInfos:      file_core_user_v1_service_proto_msgTypes,
	}.Build()
	File_core_user_v1_service_proto = out.File
	file_core_user_v1_service_proto_goTypes = nil
	file_core_user_v1_service_proto_depIdxs = nil
}
