// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/inference/v1/service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AskRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AskRequestMultiError, or
// nil if none found.
func (m *AskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for UserId

	// no validation rules for AccountId

	// no validation rules for Query

	// no validation rules for Language

	// no validation rules for TopK

	// no validation rules for Strategy

	// no validation rules for DebugMode

	if m.SessionId != nil {
		// no validation rules for SessionId
	}

	if m.Title != nil {
		// no validation rules for Title
	}

	if len(errors) > 0 {
		return AskRequestMultiError(errors)
	}

	return nil
}

// AskRequestMultiError is an error wrapping multiple validation errors
// returned by AskRequest.ValidateAll() if the designated constraints aren't met.
type AskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AskRequestMultiError) AllErrors() []error { return m }

// AskRequestValidationError is the validation error returned by
// AskRequest.Validate if the designated constraints aren't met.
type AskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AskRequestValidationError) ErrorName() string { return "AskRequestValidationError" }

// Error satisfies the builtin error interface
func (e AskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AskRequestValidationError{}

// Validate checks the field values on Citation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Citation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Citation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CitationMultiError, or nil
// if none found.
func (m *Citation) ValidateAll() error {
	return m.validate(true)
}

func (m *Citation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for ChunkId

	// no validation rules for SourceType

	// no validation rules for Score

	if m.Title != nil {
		// no validation rules for Title
	}

	if m.Excerpt != nil {
		// no validation rules for Excerpt
	}

	if len(errors) > 0 {
		return CitationMultiError(errors)
	}

	return nil
}

// CitationMultiError is an error wrapping multiple validation errors returned
// by Citation.ValidateAll() if the designated constraints aren't met.
type CitationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CitationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CitationMultiError) AllErrors() []error { return m }

// CitationValidationError is the validation error returned by
// Citation.Validate if the designated constraints aren't met.
type CitationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CitationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CitationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CitationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CitationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CitationValidationError) ErrorName() string { return "CitationValidationError" }

// Error satisfies the builtin error interface
func (e CitationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCitation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CitationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CitationValidationError{}

// Validate checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Usage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UsageMultiError, or nil if none found.
func (m *Usage) ValidateAll() error {
	return m.validate(true)
}

func (m *Usage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	if len(errors) > 0 {
		return UsageMultiError(errors)
	}

	return nil
}

// UsageMultiError is an error wrapping multiple validation errors returned by
// Usage.ValidateAll() if the designated constraints aren't met.
type UsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageMultiError) AllErrors() []error { return m }

// UsageValidationError is the validation error returned by Usage.Validate if
// the designated constraints aren't met.
type UsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageValidationError) ErrorName() string { return "UsageValidationError" }

// Error satisfies the builtin error interface
func (e UsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageValidationError{}

// Validate checks the field values on AskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AskResponseMultiError, or
// nil if none found.
func (m *AskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for SessionId

	// no validation rules for Answer

	for idx, item := range m.GetCitations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskResponseValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskResponseValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskResponseValidationError{
					field:  fmt.Sprintf("Citations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AskResponseValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AskResponseValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AskResponseValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Model

	// no validation rules for LatencyMs

	// no validation rules for SessionCreatedAt

	// no validation rules for SessionUpdatedAt

	if len(errors) > 0 {
		return AskResponseMultiError(errors)
	}

	return nil
}

// AskResponseMultiError is an error wrapping multiple validation errors
// returned by AskResponse.ValidateAll() if the designated constraints aren't met.
type AskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AskResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AskResponseMultiError) AllErrors() []error { return m }

// AskResponseValidationError is the validation error returned by
// AskResponse.Validate if the designated constraints aren't met.
type AskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AskResponseValidationError) ErrorName() string { return "AskResponseValidationError" }

// Error satisfies the builtin error interface
func (e AskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AskResponseValidationError{}

// Validate checks the field values on AskStreamChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AskStreamChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AskStreamChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AskStreamChunkMultiError,
// or nil if none found.
func (m *AskStreamChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *AskStreamChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Chunk.(type) {
	case *AskStreamChunk_Text:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetText()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Text",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Text",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetText()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "Text",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_Citations:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetCitations()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Citations",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Citations",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCitations()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "Citations",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_Done:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetDone()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Done",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Done",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDone()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "Done",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_Error:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetError()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Error",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetError()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "Error",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_ToolUse:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToolUse()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolUse",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolUse",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolUse()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "ToolUse",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_ToolResult:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToolResult()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolResult",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolResult",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolResult()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "ToolResult",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_Thinking:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetThinking()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Thinking",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "Thinking",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetThinking()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "Thinking",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AskStreamChunk_ToolSuppressed:
		if v == nil {
			err := AskStreamChunkValidationError{
				field:  "Chunk",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetToolSuppressed()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolSuppressed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskStreamChunkValidationError{
						field:  "ToolSuppressed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetToolSuppressed()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskStreamChunkValidationError{
					field:  "ToolSuppressed",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return AskStreamChunkMultiError(errors)
	}

	return nil
}

// AskStreamChunkMultiError is an error wrapping multiple validation errors
// returned by AskStreamChunk.ValidateAll() if the designated constraints
// aren't met.
type AskStreamChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AskStreamChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AskStreamChunkMultiError) AllErrors() []error { return m }

// AskStreamChunkValidationError is the validation error returned by
// AskStreamChunk.Validate if the designated constraints aren't met.
type AskStreamChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AskStreamChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AskStreamChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AskStreamChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AskStreamChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AskStreamChunkValidationError) ErrorName() string { return "AskStreamChunkValidationError" }

// Error satisfies the builtin error interface
func (e AskStreamChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAskStreamChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AskStreamChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AskStreamChunkValidationError{}

// Validate checks the field values on TextChunk with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TextChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TextChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TextChunkMultiError, or nil
// if none found.
func (m *TextChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *TextChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Text

	if len(errors) > 0 {
		return TextChunkMultiError(errors)
	}

	return nil
}

// TextChunkMultiError is an error wrapping multiple validation errors returned
// by TextChunk.ValidateAll() if the designated constraints aren't met.
type TextChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TextChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TextChunkMultiError) AllErrors() []error { return m }

// TextChunkValidationError is the validation error returned by
// TextChunk.Validate if the designated constraints aren't met.
type TextChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TextChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TextChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TextChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TextChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TextChunkValidationError) ErrorName() string { return "TextChunkValidationError" }

// Error satisfies the builtin error interface
func (e TextChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTextChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TextChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TextChunkValidationError{}

// Validate checks the field values on CitationsChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CitationsChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CitationsChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CitationsChunkMultiError,
// or nil if none found.
func (m *CitationsChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *CitationsChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCitations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CitationsChunkValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CitationsChunkValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CitationsChunkValidationError{
					field:  fmt.Sprintf("Citations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CitationsChunkMultiError(errors)
	}

	return nil
}

// CitationsChunkMultiError is an error wrapping multiple validation errors
// returned by CitationsChunk.ValidateAll() if the designated constraints
// aren't met.
type CitationsChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CitationsChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CitationsChunkMultiError) AllErrors() []error { return m }

// CitationsChunkValidationError is the validation error returned by
// CitationsChunk.Validate if the designated constraints aren't met.
type CitationsChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CitationsChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CitationsChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CitationsChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CitationsChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CitationsChunkValidationError) ErrorName() string { return "CitationsChunkValidationError" }

// Error satisfies the builtin error interface
func (e CitationsChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCitationsChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CitationsChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CitationsChunkValidationError{}

// Validate checks the field values on DoneChunk with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DoneChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DoneChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DoneChunkMultiError, or nil
// if none found.
func (m *DoneChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *DoneChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LatencyMs

	// no validation rules for Model

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DoneChunkValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DoneChunkValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DoneChunkValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SessionId

	// no validation rules for SessionCreatedAt

	// no validation rules for SessionUpdatedAt

	if len(errors) > 0 {
		return DoneChunkMultiError(errors)
	}

	return nil
}

// DoneChunkMultiError is an error wrapping multiple validation errors returned
// by DoneChunk.ValidateAll() if the designated constraints aren't met.
type DoneChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DoneChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DoneChunkMultiError) AllErrors() []error { return m }

// DoneChunkValidationError is the validation error returned by
// DoneChunk.Validate if the designated constraints aren't met.
type DoneChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DoneChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DoneChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DoneChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DoneChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DoneChunkValidationError) ErrorName() string { return "DoneChunkValidationError" }

// Error satisfies the builtin error interface
func (e DoneChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDoneChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DoneChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DoneChunkValidationError{}

// Validate checks the field values on ErrorChunk with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorChunkMultiError, or
// nil if none found.
func (m *ErrorChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return ErrorChunkMultiError(errors)
	}

	return nil
}

// ErrorChunkMultiError is an error wrapping multiple validation errors
// returned by ErrorChunk.ValidateAll() if the designated constraints aren't met.
type ErrorChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorChunkMultiError) AllErrors() []error { return m }

// ErrorChunkValidationError is the validation error returned by
// ErrorChunk.Validate if the designated constraints aren't met.
type ErrorChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorChunkValidationError) ErrorName() string { return "ErrorChunkValidationError" }

// Error satisfies the builtin error interface
func (e ErrorChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorChunkValidationError{}

// Validate checks the field values on ToolUseChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ToolUseChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolUseChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ToolUseChunkMultiError, or
// nil if none found.
func (m *ToolUseChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolUseChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Tool

	// no validation rules for ArgumentsJson

	if len(errors) > 0 {
		return ToolUseChunkMultiError(errors)
	}

	return nil
}

// ToolUseChunkMultiError is an error wrapping multiple validation errors
// returned by ToolUseChunk.ValidateAll() if the designated constraints aren't met.
type ToolUseChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolUseChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolUseChunkMultiError) AllErrors() []error { return m }

// ToolUseChunkValidationError is the validation error returned by
// ToolUseChunk.Validate if the designated constraints aren't met.
type ToolUseChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolUseChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolUseChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolUseChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolUseChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolUseChunkValidationError) ErrorName() string { return "ToolUseChunkValidationError" }

// Error satisfies the builtin error interface
func (e ToolUseChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolUseChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolUseChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolUseChunkValidationError{}

// Validate checks the field values on ToolResultChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ToolResultChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolResultChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToolResultChunkMultiError, or nil if none found.
func (m *ToolResultChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolResultChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Tool

	// no validation rules for ResultSummary

	if len(errors) > 0 {
		return ToolResultChunkMultiError(errors)
	}

	return nil
}

// ToolResultChunkMultiError is an error wrapping multiple validation errors
// returned by ToolResultChunk.ValidateAll() if the designated constraints
// aren't met.
type ToolResultChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolResultChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolResultChunkMultiError) AllErrors() []error { return m }

// ToolResultChunkValidationError is the validation error returned by
// ToolResultChunk.Validate if the designated constraints aren't met.
type ToolResultChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolResultChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolResultChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolResultChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolResultChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolResultChunkValidationError) ErrorName() string { return "ToolResultChunkValidationError" }

// Error satisfies the builtin error interface
func (e ToolResultChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolResultChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolResultChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolResultChunkValidationError{}

// Validate checks the field values on ThinkingChunk with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ThinkingChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ThinkingChunk with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ThinkingChunkMultiError, or
// nil if none found.
func (m *ThinkingChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *ThinkingChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Text

	if len(errors) > 0 {
		return ThinkingChunkMultiError(errors)
	}

	return nil
}

// ThinkingChunkMultiError is an error wrapping multiple validation errors
// returned by ThinkingChunk.ValidateAll() if the designated constraints
// aren't met.
type ThinkingChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ThinkingChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ThinkingChunkMultiError) AllErrors() []error { return m }

// ThinkingChunkValidationError is the validation error returned by
// ThinkingChunk.Validate if the designated constraints aren't met.
type ThinkingChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ThinkingChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ThinkingChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ThinkingChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ThinkingChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ThinkingChunkValidationError) ErrorName() string { return "ThinkingChunkValidationError" }

// Error satisfies the builtin error interface
func (e ThinkingChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sThinkingChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ThinkingChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ThinkingChunkValidationError{}

// Validate checks the field values on ToolSuppressedChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ToolSuppressedChunk) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ToolSuppressedChunk with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ToolSuppressedChunkMultiError, or nil if none found.
func (m *ToolSuppressedChunk) ValidateAll() error {
	return m.validate(true)
}

func (m *ToolSuppressedChunk) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Tool

	// no validation rules for Reason

	// no validation rules for MatchedQuery

	if len(errors) > 0 {
		return ToolSuppressedChunkMultiError(errors)
	}

	return nil
}

// ToolSuppressedChunkMultiError is an error wrapping multiple validation
// errors returned by ToolSuppressedChunk.ValidateAll() if the designated
// constraints aren't met.
type ToolSuppressedChunkMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ToolSuppressedChunkMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ToolSuppressedChunkMultiError) AllErrors() []error { return m }

// ToolSuppressedChunkValidationError is the validation error returned by
// ToolSuppressedChunk.Validate if the designated constraints aren't met.
type ToolSuppressedChunkValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ToolSuppressedChunkValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ToolSuppressedChunkValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ToolSuppressedChunkValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ToolSuppressedChunkValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ToolSuppressedChunkValidationError) ErrorName() string {
	return "ToolSuppressedChunkValidationError"
}

// Error satisfies the builtin error interface
func (e ToolSuppressedChunkValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sToolSuppressedChunk.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ToolSuppressedChunkValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ToolSuppressedChunkValidationError{}
