// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/inference/v1/service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AskRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AskRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AskRequestMultiError, or
// nil if none found.
func (m *AskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for UserId

	// no validation rules for AccountId

	// no validation rules for Query

	// no validation rules for Language

	// no validation rules for TopK

	if m.SessionId != nil {
		// no validation rules for SessionId
	}

	if len(errors) > 0 {
		return AskRequestMultiError(errors)
	}

	return nil
}

// AskRequestMultiError is an error wrapping multiple validation errors
// returned by AskRequest.ValidateAll() if the designated constraints aren't met.
type AskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AskRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AskRequestMultiError) AllErrors() []error { return m }

// AskRequestValidationError is the validation error returned by
// AskRequest.Validate if the designated constraints aren't met.
type AskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AskRequestValidationError) ErrorName() string { return "AskRequestValidationError" }

// Error satisfies the builtin error interface
func (e AskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AskRequestValidationError{}

// Validate checks the field values on Citation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Citation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Citation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CitationMultiError, or nil
// if none found.
func (m *Citation) ValidateAll() error {
	return m.validate(true)
}

func (m *Citation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocumentId

	// no validation rules for ChunkId

	// no validation rules for SourceType

	// no validation rules for Score

	if m.Title != nil {
		// no validation rules for Title
	}

	if len(errors) > 0 {
		return CitationMultiError(errors)
	}

	return nil
}

// CitationMultiError is an error wrapping multiple validation errors returned
// by Citation.ValidateAll() if the designated constraints aren't met.
type CitationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CitationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CitationMultiError) AllErrors() []error { return m }

// CitationValidationError is the validation error returned by
// Citation.Validate if the designated constraints aren't met.
type CitationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CitationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CitationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CitationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CitationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CitationValidationError) ErrorName() string { return "CitationValidationError" }

// Error satisfies the builtin error interface
func (e CitationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCitation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CitationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CitationValidationError{}

// Validate checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Usage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UsageMultiError, or nil if none found.
func (m *Usage) ValidateAll() error {
	return m.validate(true)
}

func (m *Usage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	if len(errors) > 0 {
		return UsageMultiError(errors)
	}

	return nil
}

// UsageMultiError is an error wrapping multiple validation errors returned by
// Usage.ValidateAll() if the designated constraints aren't met.
type UsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageMultiError) AllErrors() []error { return m }

// UsageValidationError is the validation error returned by Usage.Validate if
// the designated constraints aren't met.
type UsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageValidationError) ErrorName() string { return "UsageValidationError" }

// Error satisfies the builtin error interface
func (e UsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageValidationError{}

// Validate checks the field values on AskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AskResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AskResponseMultiError, or
// nil if none found.
func (m *AskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for SessionId

	// no validation rules for Answer

	for idx, item := range m.GetCitations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AskResponseValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AskResponseValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AskResponseValidationError{
					field:  fmt.Sprintf("Citations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AskResponseValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AskResponseValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AskResponseValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Model

	// no validation rules for LatencyMs

	if len(errors) > 0 {
		return AskResponseMultiError(errors)
	}

	return nil
}

// AskResponseMultiError is an error wrapping multiple validation errors
// returned by AskResponse.ValidateAll() if the designated constraints aren't met.
type AskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AskResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AskResponseMultiError) AllErrors() []error { return m }

// AskResponseValidationError is the validation error returned by
// AskResponse.Validate if the designated constraints aren't met.
type AskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AskResponseValidationError) ErrorName() string { return "AskResponseValidationError" }

// Error satisfies the builtin error interface
func (e AskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AskResponseValidationError{}
