// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ai/inference/v1/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIInferenceService_Ask_FullMethodName       = "/ai.inference.v1.AIInferenceService/Ask"
	AIInferenceService_AskStream_FullMethodName = "/ai.inference.v1.AIInferenceService/AskStream"
)

// AIInferenceServiceClient is the client API for AIInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIInferenceServiceClient interface {
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
	AskStream(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskStreamChunk], error)
}

type aIInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIInferenceServiceClient(cc grpc.ClientConnInterface) AIInferenceServiceClient {
	return &aIInferenceServiceClient{cc}
}

func (c *aIInferenceServiceClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, AIInferenceService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIInferenceServiceClient) AskStream(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIInferenceService_ServiceDesc.Streams[0], AIInferenceService_AskStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskRequest, AskStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIInferenceService_AskStreamClient = grpc.ServerStreamingClient[AskStreamChunk]

// AIInferenceServiceServer is the server API for AIInferenceService service.
// All implementations must embed UnimplementedAIInferenceServiceServer
// for forward compatibility.
type AIInferenceServiceServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	AskStream(*AskRequest, grpc.ServerStreamingServer[AskStreamChunk]) error
	mustEmbedUnimplementedAIInferenceServiceServer()
}

// UnimplementedAIInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIInferenceServiceServer struct{}

func (UnimplementedAIInferenceServiceServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAIInferenceServiceServer) AskStream(*AskRequest, grpc.ServerStreamingServer[AskStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method AskStream not implemented")
}
func (UnimplementedAIInferenceServiceServer) mustEmbedUnimplementedAIInferenceServiceServer() {}
func (UnimplementedAIInferenceServiceServer) testEmbeddedByValue()                            {}

// UnsafeAIInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIInferenceServiceServer will
// result in compilation errors.
type UnsafeAIInferenceServiceServer interface {
	mustEmbedUnimplementedAIInferenceServiceServer()
}

func RegisterAIInferenceServiceServer(s grpc.ServiceRegistrar, srv AIInferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedAIInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIInferenceService_ServiceDesc, srv)
}

func _AIInferenceService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIInferenceServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIInferenceService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIInferenceServiceServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIInferenceService_AskStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIInferenceServiceServer).AskStream(m, &grpc.GenericServerStream[AskRequest, AskStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIInferenceService_AskStreamServer = grpc.ServerStreamingServer[AskStreamChunk]

// AIInferenceService_ServiceDesc is the grpc.ServiceDesc for AIInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.inference.v1.AIInferenceService",
	HandlerType: (*AIInferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _AIInferenceService_Ask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AskStream",
			Handler:       _AIInferenceService_AskStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/inference/v1/service.proto",
}
