// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ai/conversation/v1/service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConversationsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListConversationsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListConversationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *SessionSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionSummary) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SessionSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SessionSummary) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SessionSummary) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MessageLimit   int32                  `protobuf:"varint,3,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"`
	MessageOffset  int32                  `protobuf:"varint,4,opt,name=message_offset,json=messageOffset,proto3" json:"message_offset,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,5,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetConversationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetConversationRequest) GetMessageLimit() int32 {
	if x != nil {
		return x.MessageLimit
	}
	return 0
}

func (x *GetConversationRequest) GetMessageOffset() int32 {
	if x != nil {
		return x.MessageOffset
	}
	return 0
}

func (x *GetConversationRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionDetail         `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Messages      []*MessageDetail       `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalMessages int32                  `protobuf:"varint,3,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationResponse) GetSession() *SessionDetail {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetConversationResponse) GetMessages() []*MessageDetail {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetConversationResponse) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

type SessionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDetail) Reset() {
	*x = SessionDetail{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDetail) ProtoMessage() {}

func (x *SessionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDetail.ProtoReflect.Descriptor instead.
func (*SessionDetail) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *SessionDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionDetail) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SessionDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SessionDetail) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SessionDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MessageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Citations     []*Citation            `protobuf:"bytes,4,rep,name=citations,proto3" json:"citations,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDetail) Reset() {
	*x = MessageDetail{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetail) ProtoMessage() {}

func (x *MessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetail.ProtoReflect.Descriptor instead.
func (*MessageDetail) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *MessageDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageDetail) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageDetail) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *MessageDetail) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *MessageDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *Citation) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Citation) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Citation) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Citation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Citation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ArchiveConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveConversationRequest) Reset() {
	*x = ArchiveConversationRequest{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConversationRequest) ProtoMessage() {}

func (x *ArchiveConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConversationRequest.ProtoReflect.Descriptor instead.
func (*ArchiveConversationRequest) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveConversationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArchiveConversationRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ArchiveConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveConversationResponse) Reset() {
	*x = ArchiveConversationResponse{}
	mi := &file_ai_conversation_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConversationResponse) ProtoMessage() {}

func (x *ArchiveConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_conversation_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConversationResponse.ProtoReflect.Descriptor instead.
func (*ArchiveConversationResponse) Descriptor() ([]byte, []int) {
	return file_ai_conversation_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ArchiveConversationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ai_conversation_v1_service_proto protoreflect.FileDescriptor

const file_ai_conversation_v1_service_proto_rawDesc = "" +
	"\n" +
	" ai/conversation/v1/service.proto\x12\x12ai.conversation.v1\x1a\x1bbuf/validate/validate.proto\"\xa8\x01\n" +
	"\x18ListConversationsRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12\x1f\n" +
	"\x05limit\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\"q\n" +
	"\x19ListConversationsResponse\x12>\n" +
	"\bsessions\x18\x01 \x03(\v2\".ai.conversation.v1.SessionSummaryR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc3\x01\n" +
	"\x0eSessionSummary\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xf4\x01\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tsessionId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12/\n" +
	"\rmessage_limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc8\x01(\x01R\fmessageLimit\x12.\n" +
	"\x0emessage_offset\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\rmessageOffset\x12'\n" +
	"\x0finclude_deleted\x18\x05 \x01(\bR\x0eincludeDeleted\"\xbc\x01\n" +
	"\x17GetConversationResponse\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.ai.conversation.v1.SessionDetailR\asession\x12=\n" +
	"\bmessages\x18\x02 \x03(\v2!.ai.conversation.v1.MessageDetailR\bmessages\x12%\n" +
	"\x0etotal_messages\x18\x03 \x01(\x05R\rtotalMessages\"\xda\x01\n" +
	"\rSessionDetail\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xe3\x01\n" +
	"\rMessageDetail\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12:\n" +
	"\tcitations\x18\x04 \x03(\v2\x1c.ai.conversation.v1.CitationR\tcitations\x12/\n" +
	"\x05usage\x18\x05 \x01(\v2\x19.ai.conversation.v1.UsageR\x05usage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xa7\x01\n" +
	"\bCitation\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\achunkId\x12)\n" +
	"\vdocument_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"documentId\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"n\n" +
	"\x1aArchiveConversationRequest\x12'\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tsessionId\x12'\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\taccountId\"7\n" +
	"\x1bArchiveConversationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xed\x02\n" +
	"\x15AIConversationService\x12p\n" +
	"\x11ListConversations\x12,.ai.conversation.v1.ListConversationsRequest\x1a-.ai.conversation.v1.ListConversationsResponse\x12j\n" +
	"\x0fGetConversation\x12*.ai.conversation.v1.GetConversationRequest\x1a+.ai.conversation.v1.GetConversationResponse\x12v\n" +
	"\x13ArchiveConversation\x12..ai.conversation.v1.ArchiveConversationRequest\x1a/.ai.conversation.v1.ArchiveConversationResponseBNZLgithub.com/Final-Year-Project-G22/backend/core-backend/pb/ai/conversation/v1b\x06proto3"

var (
	file_ai_conversation_v1_service_proto_rawDescOnce sync.Once
	file_ai_conversation_v1_service_proto_rawDescData []byte
)

func file_ai_conversation_v1_service_proto_rawDescGZIP() []byte {
	file_ai_conversation_v1_service_proto_rawDescOnce.Do(func() {
		file_ai_conversation_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_conversation_v1_service_proto_rawDesc), len(file_ai_conversation_v1_service_proto_rawDesc)))
	})
	return file_ai_conversation_v1_service_proto_rawDescData
}

var file_ai_conversation_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ai_conversation_v1_service_proto_goTypes = []any{
	(*ListConversationsRequest)(nil),    // 0: ai.conversation.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil),   // 1: ai.conversation.v1.ListConversationsResponse
	(*SessionSummary)(nil),              // 2: ai.conversation.v1.SessionSummary
	(*GetConversationRequest)(nil),      // 3: ai.conversation.v1.GetConversationRequest
	(*GetConversationResponse)(nil),     // 4: ai.conversation.v1.GetConversationResponse
	(*SessionDetail)(nil),               // 5: ai.conversation.v1.SessionDetail
	(*MessageDetail)(nil),               // 6: ai.conversation.v1.MessageDetail
	(*Citation)(nil),                    // 7: ai.conversation.v1.Citation
	(*Usage)(nil),                       // 8: ai.conversation.v1.Usage
	(*ArchiveConversationRequest)(nil),  // 9: ai.conversation.v1.ArchiveConversationRequest
	(*ArchiveConversationResponse)(nil), // 10: ai.conversation.v1.ArchiveConversationResponse
}
var file_ai_conversation_v1_service_proto_depIdxs = []int32{
	2,  // 0: ai.conversation.v1.ListConversationsResponse.sessions:type_name -> ai.conversation.v1.SessionSummary
	5,  // 1: ai.conversation.v1.GetConversationResponse.session:type_name -> ai.conversation.v1.SessionDetail
	6,  // 2: ai.conversation.v1.GetConversationResponse.messages:type_name -> ai.conversation.v1.MessageDetail
	7,  // 3: ai.conversation.v1.MessageDetail.citations:type_name -> ai.conversation.v1.Citation
	8,  // 4: ai.conversation.v1.MessageDetail.usage:type_name -> ai.conversation.v1.Usage
	0,  // 5: ai.conversation.v1.AIConversationService.ListConversations:input_type -> ai.conversation.v1.ListConversationsRequest
	3,  // 6: ai.conversation.v1.AIConversationService.GetConversation:input_type -> ai.conversation.v1.GetConversationRequest
	9,  // 7: ai.conversation.v1.AIConversationService.ArchiveConversation:input_type -> ai.conversation.v1.ArchiveConversationRequest
	1,  // 8: ai.conversation.v1.AIConversationService.ListConversations:output_type -> ai.conversation.v1.ListConversationsResponse
	4,  // 9: ai.conversation.v1.AIConversationService.GetConversation:output_type -> ai.conversation.v1.GetConversationResponse
	10, // 10: ai.conversation.v1.AIConversationService.ArchiveConversation:output_type -> ai.conversation.v1.ArchiveConversationResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ai_conversation_v1_service_proto_init() }
func file_ai_conversation_v1_service_proto_init() {
	if File_ai_conversation_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_conversation_v1_service_proto_rawDesc), len(file_ai_conversation_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_conversation_v1_service_proto_goTypes,
		DependencyIndexes: file_ai_conversation_v1_service_proto_depIdxs,
		MessageInfos:      file_ai_conversation_v1_service_proto_msgTypes,
	}.Build()
	File_ai_conversation_v1_service_proto = out.File
	file_ai_conversation_v1_service_proto_goTypes = nil
	file_ai_conversation_v1_service_proto_depIdxs = nil
}
