// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ai/conversation/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListConversationsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListConversationsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConversationsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConversationsRequestMultiError, or nil if none found.
func (m *ListConversationsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConversationsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for AccountId

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListConversationsRequestMultiError(errors)
	}

	return nil
}

// ListConversationsRequestMultiError is an error wrapping multiple validation
// errors returned by ListConversationsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListConversationsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConversationsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConversationsRequestMultiError) AllErrors() []error { return m }

// ListConversationsRequestValidationError is the validation error returned by
// ListConversationsRequest.Validate if the designated constraints aren't met.
type ListConversationsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConversationsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConversationsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConversationsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConversationsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConversationsRequestValidationError) ErrorName() string {
	return "ListConversationsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListConversationsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConversationsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConversationsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConversationsRequestValidationError{}

// Validate checks the field values on ListConversationsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListConversationsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListConversationsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListConversationsResponseMultiError, or nil if none found.
func (m *ListConversationsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListConversationsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSessions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListConversationsResponseValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListConversationsResponseValidationError{
						field:  fmt.Sprintf("Sessions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListConversationsResponseValidationError{
					field:  fmt.Sprintf("Sessions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListConversationsResponseMultiError(errors)
	}

	return nil
}

// ListConversationsResponseMultiError is an error wrapping multiple validation
// errors returned by ListConversationsResponse.ValidateAll() if the
// designated constraints aren't met.
type ListConversationsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListConversationsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListConversationsResponseMultiError) AllErrors() []error { return m }

// ListConversationsResponseValidationError is the validation error returned by
// ListConversationsResponse.Validate if the designated constraints aren't met.
type ListConversationsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListConversationsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListConversationsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListConversationsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListConversationsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListConversationsResponseValidationError) ErrorName() string {
	return "ListConversationsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListConversationsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListConversationsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListConversationsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListConversationsResponseValidationError{}

// Validate checks the field values on SessionSummary with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SessionSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SessionSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SessionSummaryMultiError,
// or nil if none found.
func (m *SessionSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *SessionSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AccountId

	// no validation rules for Title

	// no validation rules for Language

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return SessionSummaryMultiError(errors)
	}

	return nil
}

// SessionSummaryMultiError is an error wrapping multiple validation errors
// returned by SessionSummary.ValidateAll() if the designated constraints
// aren't met.
type SessionSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SessionSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SessionSummaryMultiError) AllErrors() []error { return m }

// SessionSummaryValidationError is the validation error returned by
// SessionSummary.Validate if the designated constraints aren't met.
type SessionSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SessionSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SessionSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SessionSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SessionSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SessionSummaryValidationError) ErrorName() string { return "SessionSummaryValidationError" }

// Error satisfies the builtin error interface
func (e SessionSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSessionSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SessionSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SessionSummaryValidationError{}

// Validate checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetConversationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetConversationRequestMultiError, or nil if none found.
func (m *GetConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionId

	// no validation rules for AccountId

	// no validation rules for MessageLimit

	// no validation rules for MessageOffset

	// no validation rules for IncludeDeleted

	if len(errors) > 0 {
		return GetConversationRequestMultiError(errors)
	}

	return nil
}

// GetConversationRequestMultiError is an error wrapping multiple validation
// errors returned by GetConversationRequest.ValidateAll() if the designated
// constraints aren't met.
type GetConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetConversationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetConversationRequestMultiError) AllErrors() []error { return m }

// GetConversationRequestValidationError is the validation error returned by
// GetConversationRequest.Validate if the designated constraints aren't met.
type GetConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetConversationRequestValidationError) ErrorName() string {
	return "GetConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetConversationRequestValidationError{}

// Validate checks the field values on GetConversationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetConversationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetConversationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetConversationResponseMultiError, or nil if none found.
func (m *GetConversationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetConversationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSession()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetConversationResponseValidationError{
					field:  "Session",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetConversationResponseValidationError{
					field:  "Session",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSession()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetConversationResponseValidationError{
				field:  "Session",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetMessages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetConversationResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetConversationResponseValidationError{
						field:  fmt.Sprintf("Messages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetConversationResponseValidationError{
					field:  fmt.Sprintf("Messages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalMessages

	if len(errors) > 0 {
		return GetConversationResponseMultiError(errors)
	}

	return nil
}

// GetConversationResponseMultiError is an error wrapping multiple validation
// errors returned by GetConversationResponse.ValidateAll() if the designated
// constraints aren't met.
type GetConversationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetConversationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetConversationResponseMultiError) AllErrors() []error { return m }

// GetConversationResponseValidationError is the validation error returned by
// GetConversationResponse.Validate if the designated constraints aren't met.
type GetConversationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetConversationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetConversationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetConversationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetConversationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetConversationResponseValidationError) ErrorName() string {
	return "GetConversationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetConversationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetConversationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetConversationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetConversationResponseValidationError{}

// Validate checks the field values on SessionDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SessionDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SessionDetail with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SessionDetailMultiError, or
// nil if none found.
func (m *SessionDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *SessionDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AccountId

	// no validation rules for Title

	// no validation rules for Language

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return SessionDetailMultiError(errors)
	}

	return nil
}

// SessionDetailMultiError is an error wrapping multiple validation errors
// returned by SessionDetail.ValidateAll() if the designated constraints
// aren't met.
type SessionDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SessionDetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SessionDetailMultiError) AllErrors() []error { return m }

// SessionDetailValidationError is the validation error returned by
// SessionDetail.Validate if the designated constraints aren't met.
type SessionDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SessionDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SessionDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SessionDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SessionDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SessionDetailValidationError) ErrorName() string { return "SessionDetailValidationError" }

// Error satisfies the builtin error interface
func (e SessionDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSessionDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SessionDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SessionDetailValidationError{}

// Validate checks the field values on MessageDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessageDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessageDetail with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessageDetailMultiError, or
// nil if none found.
func (m *MessageDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *MessageDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Role

	// no validation rules for Content

	for idx, item := range m.GetCitations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MessageDetailValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MessageDetailValidationError{
						field:  fmt.Sprintf("Citations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MessageDetailValidationError{
					field:  fmt.Sprintf("Citations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetUsage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MessageDetailValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MessageDetailValidationError{
					field:  "Usage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUsage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MessageDetailValidationError{
				field:  "Usage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return MessageDetailMultiError(errors)
	}

	return nil
}

// MessageDetailMultiError is an error wrapping multiple validation errors
// returned by MessageDetail.ValidateAll() if the designated constraints
// aren't met.
type MessageDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessageDetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessageDetailMultiError) AllErrors() []error { return m }

// MessageDetailValidationError is the validation error returned by
// MessageDetail.Validate if the designated constraints aren't met.
type MessageDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageDetailValidationError) ErrorName() string { return "MessageDetailValidationError" }

// Error satisfies the builtin error interface
func (e MessageDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessageDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageDetailValidationError{}

// Validate checks the field values on Citation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Citation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Citation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CitationMultiError, or nil
// if none found.
func (m *Citation) ValidateAll() error {
	return m.validate(true)
}

func (m *Citation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ChunkId

	// no validation rules for DocumentId

	// no validation rules for SourceType

	// no validation rules for Title

	// no validation rules for Score

	if len(errors) > 0 {
		return CitationMultiError(errors)
	}

	return nil
}

// CitationMultiError is an error wrapping multiple validation errors returned
// by Citation.ValidateAll() if the designated constraints aren't met.
type CitationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CitationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CitationMultiError) AllErrors() []error { return m }

// CitationValidationError is the validation error returned by
// Citation.Validate if the designated constraints aren't met.
type CitationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CitationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CitationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CitationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CitationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CitationValidationError) ErrorName() string { return "CitationValidationError" }

// Error satisfies the builtin error interface
func (e CitationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCitation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CitationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CitationValidationError{}

// Validate checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Usage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Usage with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UsageMultiError, or nil if none found.
func (m *Usage) ValidateAll() error {
	return m.validate(true)
}

func (m *Usage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PromptTokens

	// no validation rules for CompletionTokens

	// no validation rules for TotalTokens

	if len(errors) > 0 {
		return UsageMultiError(errors)
	}

	return nil
}

// UsageMultiError is an error wrapping multiple validation errors returned by
// Usage.ValidateAll() if the designated constraints aren't met.
type UsageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UsageMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UsageMultiError) AllErrors() []error { return m }

// UsageValidationError is the validation error returned by Usage.Validate if
// the designated constraints aren't met.
type UsageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UsageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UsageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UsageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UsageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UsageValidationError) ErrorName() string { return "UsageValidationError" }

// Error satisfies the builtin error interface
func (e UsageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUsage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UsageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UsageValidationError{}

// Validate checks the field values on ArchiveConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ArchiveConversationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArchiveConversationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArchiveConversationRequestMultiError, or nil if none found.
func (m *ArchiveConversationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ArchiveConversationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionId

	// no validation rules for AccountId

	if len(errors) > 0 {
		return ArchiveConversationRequestMultiError(errors)
	}

	return nil
}

// ArchiveConversationRequestMultiError is an error wrapping multiple
// validation errors returned by ArchiveConversationRequest.ValidateAll() if
// the designated constraints aren't met.
type ArchiveConversationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArchiveConversationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArchiveConversationRequestMultiError) AllErrors() []error { return m }

// ArchiveConversationRequestValidationError is the validation error returned
// by ArchiveConversationRequest.Validate if the designated constraints aren't met.
type ArchiveConversationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArchiveConversationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArchiveConversationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArchiveConversationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArchiveConversationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArchiveConversationRequestValidationError) ErrorName() string {
	return "ArchiveConversationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ArchiveConversationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArchiveConversationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArchiveConversationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArchiveConversationRequestValidationError{}

// Validate checks the field values on ArchiveConversationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ArchiveConversationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArchiveConversationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArchiveConversationResponseMultiError, or nil if none found.
func (m *ArchiveConversationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ArchiveConversationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return ArchiveConversationResponseMultiError(errors)
	}

	return nil
}

// ArchiveConversationResponseMultiError is an error wrapping multiple
// validation errors returned by ArchiveConversationResponse.ValidateAll() if
// the designated constraints aren't met.
type ArchiveConversationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArchiveConversationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArchiveConversationResponseMultiError) AllErrors() []error { return m }

// ArchiveConversationResponseValidationError is the validation error returned
// by ArchiveConversationResponse.Validate if the designated constraints
// aren't met.
type ArchiveConversationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArchiveConversationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArchiveConversationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArchiveConversationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArchiveConversationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArchiveConversationResponseValidationError) ErrorName() string {
	return "ArchiveConversationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ArchiveConversationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArchiveConversationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArchiveConversationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArchiveConversationResponseValidationError{}
