from __future__ import annotations

DEFAULT_VECTOR_TOP_K = 8
DEFAULT_BM25_TOP_K = 8
DEFAULT_SESSION_LIST_LIMIT = 20
DEFAULT_MAX_CONTEXT_HITS = 12
DEFAULT_MAX_OUTPUT_TOKENS = 1024
DEFAULT_LLM_TEMPERATURE = 0.2

MIN_TOP_K = 1
MAX_TOP_K = 50
MAX_PROMPT_LENGTH = 32768

__all__ = [
    "DEFAULT_BM25_TOP_K",
    "DEFAULT_LLM_TEMPERATURE",
    "DEFAULT_MAX_CONTEXT_HITS",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "DEFAULT_SESSION_LIST_LIMIT",
    "DEFAULT_VECTOR_TOP_K",
    "MAX_PROMPT_LENGTH",
    "MAX_TOP_K",
    "MIN_TOP_K",
]
